fof(f615, plain, $false, inference(subsumption_resolution, [], [f614, f176])).
fof(f176, plain, aRewritingSystem0(xR), inference(cnf_transformation, [], [f15])).
fof(f15, plain, aRewritingSystem0(xR), file('/home/ubuntu/library/tptp/Problems/COM/COM018+4.p', m__656)).
fof(f614, plain, ~ aRewritingSystem0(xR), inference(subsumption_resolution, [], [f613, f193])).
fof(f193, plain, isTerminating0(xR), inference(cnf_transformation, [], [f107])).
fof(f107, plain, (isTerminating0(xR) & ! [X0, X1] : (iLess0(X1, X0) | (~ sdtmndtplgtdt0(X0, xR, X1) & ! [X2] : (~ sdtmndtplgtdt0(X2, xR, X1) | ~ aReductOfIn0(X2, X0, xR) | ~ aElement0(X2)) & ~ aReductOfIn0(X1, X0, xR)) | ~ aElement0(X1) | ~ aElement0(X0)) & isLocallyConfluent0(xR) & ! [X3, X4, X5] : ((sdtmndtasgtdt0(X5, xR, sK22(X4, X5)) & ((sdtmndtplgtdt0(X5, xR, sK22(X4, X5)) & ((sdtmndtplgtdt0(sK23(X4, X5), xR, sK22(X4, X5)) & aReductOfIn0(sK23(X4, X5), X5, xR) & aElement0(sK23(X4, X5))) | aReductOfIn0(sK22(X4, X5), X5, xR))) | (sK22(X4, X5) = X5)) & sdtmndtasgtdt0(X4, xR, sK22(X4, X5)) & sP4(sK22(X4, X5), X4) & aElement0(sK22(X4, X5))) | ~ aReductOfIn0(X5, X3, xR) | ~ aReductOfIn0(X4, X3, xR) | ~ aElement0(X5) | ~ aElement0(X4) | ~ aElement0(X3))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK22, sK23])], [f66, f106, f105])).
fof(f105, plain, ! [X5, X4] : (? [X6] : (sdtmndtasgtdt0(X5, xR, X6) & ((sdtmndtplgtdt0(X5, xR, X6) & (? [X7] : (sdtmndtplgtdt0(X7, xR, X6) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) | aReductOfIn0(X6, X5, xR))) | (X5 = X6)) & sdtmndtasgtdt0(X4, xR, X6) & sP4(X6, X4) & aElement0(X6)) => (sdtmndtasgtdt0(X5, xR, sK22(X4, X5)) & ((sdtmndtplgtdt0(X5, xR, sK22(X4, X5)) & (? [X7] : (sdtmndtplgtdt0(X7, xR, sK22(X4, X5)) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) | aReductOfIn0(sK22(X4, X5), X5, xR))) | (sK22(X4, X5) = X5)) & sdtmndtasgtdt0(X4, xR, sK22(X4, X5)) & sP4(sK22(X4, X5), X4) & aElement0(sK22(X4, X5)))), introduced(choice_axiom, [])).
fof(f106, plain, ! [X5, X4] : (? [X7] : (sdtmndtplgtdt0(X7, xR, sK22(X4, X5)) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) => (sdtmndtplgtdt0(sK23(X4, X5), xR, sK22(X4, X5)) & aReductOfIn0(sK23(X4, X5), X5, xR) & aElement0(sK23(X4, X5)))), introduced(choice_axiom, [])).
fof(f66, plain, (isTerminating0(xR) & ! [X0, X1] : (iLess0(X1, X0) | (~ sdtmndtplgtdt0(X0, xR, X1) & ! [X2] : (~ sdtmndtplgtdt0(X2, xR, X1) | ~ aReductOfIn0(X2, X0, xR) | ~ aElement0(X2)) & ~ aReductOfIn0(X1, X0, xR)) | ~ aElement0(X1) | ~ aElement0(X0)) & isLocallyConfluent0(xR) & ! [X3, X4, X5] : (? [X6] : (sdtmndtasgtdt0(X5, xR, X6) & ((sdtmndtplgtdt0(X5, xR, X6) & (? [X7] : (sdtmndtplgtdt0(X7, xR, X6) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) | aReductOfIn0(X6, X5, xR))) | (X5 = X6)) & sdtmndtasgtdt0(X4, xR, X6) & sP4(X6, X4) & aElement0(X6)) | ~ aReductOfIn0(X5, X3, xR) | ~ aReductOfIn0(X4, X3, xR) | ~ aElement0(X5) | ~ aElement0(X4) | ~ aElement0(X3))), inference(definition_folding, [], [f55, e65])).
fof(f65, plain, ! [X6, X4] : ((sdtmndtplgtdt0(X4, xR, X6) & (? [X8] : (sdtmndtplgtdt0(X8, xR, X6) & aReductOfIn0(X8, X4, xR) & aElement0(X8)) | aReductOfIn0(X6, X4, xR))) | (X4 = X6) | ~ sP4(X6, X4)), inference(usedef, [], [e65])).
fof(e65, plain, ! [X6, X4] : (sP4(X6, X4) <=> ((sdtmndtplgtdt0(X4, xR, X6) & (? [X8] : (sdtmndtplgtdt0(X8, xR, X6) & aReductOfIn0(X8, X4, xR) & aElement0(X8)) | aReductOfIn0(X6, X4, xR))) | (X4 = X6))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP4])])).
fof(f55, plain, (isTerminating0(xR) & ! [X0, X1] : (iLess0(X1, X0) | (~ sdtmndtplgtdt0(X0, xR, X1) & ! [X2] : (~ sdtmndtplgtdt0(X2, xR, X1) | ~ aReductOfIn0(X2, X0, xR) | ~ aElement0(X2)) & ~ aReductOfIn0(X1, X0, xR)) | ~ aElement0(X1) | ~ aElement0(X0)) & isLocallyConfluent0(xR) & ! [X3, X4, X5] : (? [X6] : (sdtmndtasgtdt0(X5, xR, X6) & ((sdtmndtplgtdt0(X5, xR, X6) & (? [X7] : (sdtmndtplgtdt0(X7, xR, X6) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) | aReductOfIn0(X6, X5, xR))) | (X5 = X6)) & sdtmndtasgtdt0(X4, xR, X6) & ((sdtmndtplgtdt0(X4, xR, X6) & (? [X8] : (sdtmndtplgtdt0(X8, xR, X6) & aReductOfIn0(X8, X4, xR) & aElement0(X8)) | aReductOfIn0(X6, X4, xR))) | (X4 = X6)) & aElement0(X6)) | ~ aReductOfIn0(X5, X3, xR) | ~ aReductOfIn0(X4, X3, xR) | ~ aElement0(X5) | ~ aElement0(X4) | ~ aElement0(X3))), inference(flattening, [], [f54])).
fof(f54, plain, (isTerminating0(xR) & ! [X0, X1] : ((iLess0(X1, X0) | (~ sdtmndtplgtdt0(X0, xR, X1) & ! [X2] : (~ sdtmndtplgtdt0(X2, xR, X1) | ~ aReductOfIn0(X2, X0, xR) | ~ aElement0(X2)) & ~ aReductOfIn0(X1, X0, xR))) | (~ aElement0(X1) | ~ aElement0(X0))) & isLocallyConfluent0(xR) & ! [X3, X4, X5] : (? [X6] : (sdtmndtasgtdt0(X5, xR, X6) & ((sdtmndtplgtdt0(X5, xR, X6) & (? [X7] : (sdtmndtplgtdt0(X7, xR, X6) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) | aReductOfIn0(X6, X5, xR))) | (X5 = X6)) & sdtmndtasgtdt0(X4, xR, X6) & ((sdtmndtplgtdt0(X4, xR, X6) & (? [X8] : (sdtmndtplgtdt0(X8, xR, X6) & aReductOfIn0(X8, X4, xR) & aElement0(X8)) | aReductOfIn0(X6, X4, xR))) | (X4 = X6)) & aElement0(X6)) | (~ aReductOfIn0(X5, X3, xR) | ~ aReductOfIn0(X4, X3, xR) | ~ aElement0(X5) | ~ aElement0(X4) | ~ aElement0(X3)))), inference(ennf_transformation, [], [f29])).
fof(f29, plain, (isTerminating0(xR) & ! [X0, X1] : ((aElement0(X1) & aElement0(X0)) => ((sdtmndtplgtdt0(X0, xR, X1) | ? [X2] : (sdtmndtplgtdt0(X2, xR, X1) & aReductOfIn0(X2, X0, xR) & aElement0(X2)) | aReductOfIn0(X1, X0, xR)) => iLess0(X1, X0))) & isLocallyConfluent0(xR) & ! [X3, X4, X5] : ((aReductOfIn0(X5, X3, xR) & aReductOfIn0(X4, X3, xR) & aElement0(X5) & aElement0(X4) & aElement0(X3)) => ? [X6] : (sdtmndtasgtdt0(X5, xR, X6) & ((sdtmndtplgtdt0(X5, xR, X6) & (? [X7] : (sdtmndtplgtdt0(X7, xR, X6) & aReductOfIn0(X7, X5, xR) & aElement0(X7)) | aReductOfIn0(X6, X5, xR))) | (X5 = X6)) & sdtmndtasgtdt0(X4, xR, X6) & ((sdtmndtplgtdt0(X4, xR, X6) & (? [X8] : (sdtmndtplgtdt0(X8, xR, X6) & aReductOfIn0(X8, X4, xR) & aElement0(X8)) | aReductOfIn0(X6, X4, xR))) | (X4 = X6)) & aElement0(X6)))), inference(rectify, [], [f16])).
fof(f16, plain, (isTerminating0(xR) & ! [X0, X1] : ((aElement0(X1) & aElement0(X0)) => ((sdtmndtplgtdt0(X0, xR, X1) | ? [X2] : (sdtmndtplgtdt0(X2, xR, X1) & aReductOfIn0(X2, X0, xR) & aElement0(X2)) | aReductOfIn0(X1, X0, xR)) => iLess0(X1, X0))) & isLocallyConfluent0(xR) & ! [X0, X1, X2] : ((aReductOfIn0(X2, X0, xR) & aReductOfIn0(X1, X0, xR) & aElement0(X2) & aElement0(X1) & aElement0(X0)) => ? [X3] : (sdtmndtasgtdt0(X2, xR, X3) & ((sdtmndtplgtdt0(X2, xR, X3) & (? [X4] : (sdtmndtplgtdt0(X4, xR, X3) & aReductOfIn0(X4, X2, xR) & aElement0(X4)) | aReductOfIn0(X3, X2, xR))) | (X2 = X3)) & sdtmndtasgtdt0(X1, xR, X3) & ((sdtmndtplgtdt0(X1, xR, X3) & (? [X4] : (sdtmndtplgtdt0(X4, xR, X3) & aReductOfIn0(X4, X1, xR) & aElement0(X4)) | aReductOfIn0(X3, X1, xR))) | (X1 = X3)) & aElement0(X3)))), file('/home/ubuntu/library/tptp/Problems/COM/COM018+4.p', m__656_01)).
fof(f613, plain, (~ isTerminating0(xR) | ~ aRewritingSystem0(xR)), inference(subsumption_resolution, [], [f612, f241])).
fof(f241, plain, aElement0(xw), inference(cnf_transformation, [], [f128])).
fof(f128, plain, (sdtmndtasgtdt0(xv, xR, xw) & ((sdtmndtplgtdt0(xv, xR, xw) & ((sdtmndtplgtdt0(sK31, xR, xw) & aReductOfIn0(sK31, xv, xR) & aElement0(sK31)) | aReductOfIn0(xw, xv, xR))) | (xv = xw)) & sdtmndtasgtdt0(xu, xR, xw) & ((sdtmndtplgtdt0(xu, xR, xw) & ((sdtmndtplgtdt0(sK32, xR, xw) & aReductOfIn0(sK32, xu, xR) & aElement0(sK32)) | aReductOfIn0(xw, xu, xR))) | (xu = xw)) & aElement0(xw)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK31, sK32])], [f32, f127, f126])).
fof(f126, plain, (? [X0] : (sdtmndtplgtdt0(X0, xR, xw) & aReductOfIn0(X0, xv, xR) & aElement0(X0)) => (sdtmndtplgtdt0(sK31, xR, xw) & aReductOfIn0(sK31, xv, xR) & aElement0(sK31))), introduced(choice_axiom, [])).
fof(f127, plain, (? [X1] : (sdtmndtplgtdt0(X1, xR, xw) & aReductOfIn0(X1, xu, xR) & aElement0(X1)) => (sdtmndtplgtdt0(sK32, xR, xw) & aReductOfIn0(sK32, xu, xR) & aElement0(sK32))), introduced(choice_axiom, [])).
fof(f32, plain, (sdtmndtasgtdt0(xv, xR, xw) & ((sdtmndtplgtdt0(xv, xR, xw) & (? [X0] : (sdtmndtplgtdt0(X0, xR, xw) & aReductOfIn0(X0, xv, xR) & aElement0(X0)) | aReductOfIn0(xw, xv, xR))) | (xv = xw)) & sdtmndtasgtdt0(xu, xR, xw) & ((sdtmndtplgtdt0(xu, xR, xw) & (? [X1] : (sdtmndtplgtdt0(X1, xR, xw) & aReductOfIn0(X1, xu, xR) & aElement0(X1)) | aReductOfIn0(xw, xu, xR))) | (xu = xw)) & aElement0(xw)), inference(rectify, [], [f22])).
fof(f22, plain, (sdtmndtasgtdt0(xv, xR, xw) & ((sdtmndtplgtdt0(xv, xR, xw) & (? [X0] : (sdtmndtplgtdt0(X0, xR, xw) & aReductOfIn0(X0, xv, xR) & aElement0(X0)) | aReductOfIn0(xw, xv, xR))) | (xv = xw)) & sdtmndtasgtdt0(xu, xR, xw) & ((sdtmndtplgtdt0(xu, xR, xw) & (? [X0] : (sdtmndtplgtdt0(X0, xR, xw) & aReductOfIn0(X0, xu, xR) & aElement0(X0)) | aReductOfIn0(xw, xu, xR))) | (xu = xw)) & aElement0(xw)), file('/home/ubuntu/library/tptp/Problems/COM/COM018+4.p', m__799)).
fof(f612, plain, (~ aElement0(xw) | ~ isTerminating0(xR) | ~ aRewritingSystem0(xR)), inference(resolution, [], [f257, f175])).
fof(f175, plain, ! [X0, X1] : (aNormalFormOfIn0(sK20(X0, X1), X1, X0) | ~ aElement0(X1) | ~ isTerminating0(X0) | ~ aRewritingSystem0(X0)), inference(cnf_transformation, [], [f100])).
fof(f100, plain, ! [X0] : (! [X1] : (aNormalFormOfIn0(sK20(X0, X1), X1, X0) | ~ aElement0(X1)) | ~ isTerminating0(X0) | ~ aRewritingSystem0(X0)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK20])], [f53, f99])).
fof(f99, plain, ! [X1, X0] : (? [X2] : aNormalFormOfIn0(X2, X1, X0) => aNormalFormOfIn0(sK20(X0, X1), X1, X0)), introduced(choice_axiom, [])).
fof(f53, plain, ! [X0] : (! [X1] : (? [X2] : aNormalFormOfIn0(X2, X1, X0) | ~ aElement0(X1)) | ~ isTerminating0(X0) | ~ aRewritingSystem0(X0)), inference(flattening, [], [f52])).
fof(f52, plain, ! [X0] : (! [X1] : (? [X2] : aNormalFormOfIn0(X2, X1, X0) | ~ aElement0(X1)) | (~ isTerminating0(X0) | ~ aRewritingSystem0(X0))), inference(ennf_transformation, [], [f14])).
fof(f14, plain, ! [X0] : ((isTerminating0(X0) & aRewritingSystem0(X0)) => ! [X1] : (aElement0(X1) => ? [X2] : aNormalFormOfIn0(X2, X1, X0))), file('/home/ubuntu/library/tptp/Problems/COM/COM018+4.p', mTermNF)).
fof(f257, plain, ! [X0] : ~ aNormalFormOfIn0(X0, xw, xR), inference(cnf_transformation, [], [f130])).
fof(f130, plain, ! [X0] : (~ aNormalFormOfIn0(X0, xw, xR) & (aReductOfIn0(sK33(X0), X0, xR) | (~ sdtmndtasgtdt0(xw, xR, X0) & ~ sdtmndtplgtdt0(xw, xR, X0) & ! [X2] : (~ sdtmndtplgtdt0(X2, xR, X0) | ~ aReductOfIn0(X2, xw, xR) | ~ aElement0(X2)) & ~ aReductOfIn0(X0, xw, xR) & ~ (xw = X0)) | ~ aElement0(X0))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK33])], [f58, f129])).
fof(f129, plain, ! [X0] : (? [X1] : aReductOfIn0(X1, X0, xR) => aReductOfIn0(sK33(X0), X0, xR)), introduced(choice_axiom, [])).
fof(f58, plain, ! [X0] : (~ aNormalFormOfIn0(X0, xw, xR) & (? [X1] : aReductOfIn0(X1, X0, xR) | (~ sdtmndtasgtdt0(xw, xR, X0) & ~ sdtmndtplgtdt0(xw, xR, X0) & ! [X2] : (~ sdtmndtplgtdt0(X2, xR, X0) | ~ aReductOfIn0(X2, xw, xR) | ~ aElement0(X2)) & ~ aReductOfIn0(X0, xw, xR) & ~ (xw = X0)) | ~ aElement0(X0))), inference(ennf_transformation, [], [f33])).
fof(f33, plain, ~ ? [X0] : (aNormalFormOfIn0(X0, xw, xR) | (~ ? [X1] : aReductOfIn0(X1, X0, xR) & (sdtmndtasgtdt0(xw, xR, X0) | sdtmndtplgtdt0(xw, xR, X0) | ? [X2] : (sdtmndtplgtdt0(X2, xR, X0) & aReductOfIn0(X2, xw, xR) & aElement0(X2)) | aReductOfIn0(X0, xw, xR) | (xw = X0)) & aElement0(X0))), inference(rectify, [], [f24])).
fof(f24, plain, ~ ? [X0] : (aNormalFormOfIn0(X0, xw, xR) | (~ ? [X1] : aReductOfIn0(X1, X0, xR) & (sdtmndtasgtdt0(xw, xR, X0) | sdtmndtplgtdt0(xw, xR, X0) | ? [X1] : (sdtmndtplgtdt0(X1, xR, X0) & aReductOfIn0(X1, xw, xR) & aElement0(X1)) | aReductOfIn0(X0, xw, xR) | (xw = X0)) & aElement0(X0))), inference(negated_conjecture, [], [f23])).
fof(f23, plain, ~ ? [X0] : (aNormalFormOfIn0(X0, xw, xR) | (~ ? [X1] : aReductOfIn0(X1, X0, xR) & (sdtmndtasgtdt0(xw, xR, X0) | sdtmndtplgtdt0(xw, xR, X0) | ? [X1] : (sdtmndtplgtdt0(X1, xR, X0) & aReductOfIn0(X1, xw, xR) & aElement0(X1)) | aReductOfIn0(X0, xw, xR) | (xw = X0)) & aElement0(X0))), file('/home/ubuntu/library/tptp/Problems/COM/COM018+4.p', m__)).