fof(f295, plain, $false, inference(resolution, [], [f268, f276])).
fof(f276, plain, ! [X0] : ~ aSupremumOfIn0(X0, xT, xS), inference(cnf_transformation, [], [f152])).
fof(f152, plain, ! [X0] : (~ aSupremumOfIn0(X0, xT, xS) & (sP3(X0) | (~ aUpperBoundOfIn0(X0, xT, xS) & ((~ sdtlseqdt0(sK23(X0), X0) & aElementOf0(sK23(X0), xT)) | ~ aElementOf0(X0, xS))) | ~ aElementOf0(X0, xS))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK23])], [f150, f151])).
fof(f151, plain, ! [X0] : (? [X1] : (~ sdtlseqdt0(X1, X0) & aElementOf0(X1, xT)) => (~ sdtlseqdt0(sK23(X0), X0) & aElementOf0(sK23(X0), xT))), introduced(choice_axiom, [])).
fof(f150, plain, ! [X0] : (~ aSupremumOfIn0(X0, xT, xS) & (sP3(X0) | (~ aUpperBoundOfIn0(X0, xT, xS) & (? [X1] : (~ sdtlseqdt0(X1, X0) & aElementOf0(X1, xT)) | ~ aElementOf0(X0, xS))) | ~ aElementOf0(X0, xS))), inference(rectify, [], [f85])).
fof(f85, plain, ! [X0] : (~ aSupremumOfIn0(X0, xT, xS) & (sP3(X0) | (~ aUpperBoundOfIn0(X0, xT, xS) & (? [X3] : (~ sdtlseqdt0(X3, X0) & aElementOf0(X3, xT)) | ~ aElementOf0(X0, xS))) | ~ aElementOf0(X0, xS))), inference(definition_folding, [], [f79, e84])).
fof(f84, plain, ! [X0] : (? [X1] : (~ sdtlseqdt0(X0, X1) & aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (sdtlseqdt0(X2, X1) | ~ aElementOf0(X2, xT)) & aElementOf0(X1, xS)) | ~ sP3(X0)), inference(usedef, [], [e84])).
fof(e84, plain, ! [X0] : (sP3(X0) <=> ? [X1] : (~ sdtlseqdt0(X0, X1) & aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (sdtlseqdt0(X2, X1) | ~ aElementOf0(X2, xT)) & aElementOf0(X1, xS))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP3])])).
fof(f79, plain, ! [X0] : (~ aSupremumOfIn0(X0, xT, xS) & (? [X1] : (~ sdtlseqdt0(X0, X1) & aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (sdtlseqdt0(X2, X1) | ~ aElementOf0(X2, xT)) & aElementOf0(X1, xS)) | (~ aUpperBoundOfIn0(X0, xT, xS) & (? [X3] : (~ sdtlseqdt0(X3, X0) & aElementOf0(X3, xT)) | ~ aElementOf0(X0, xS))) | ~ aElementOf0(X0, xS))), inference(flattening, [], [f78])).
fof(f78, plain, ! [X0] : (~ aSupremumOfIn0(X0, xT, xS) & (? [X1] : (~ sdtlseqdt0(X0, X1) & (aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (sdtlseqdt0(X2, X1) | ~ aElementOf0(X2, xT)) & aElementOf0(X1, xS))) | (~ aUpperBoundOfIn0(X0, xT, xS) & (? [X3] : (~ sdtlseqdt0(X3, X0) & aElementOf0(X3, xT)) | ~ aElementOf0(X0, xS))) | ~ aElementOf0(X0, xS))), inference(ennf_transformation, [], [f42])).
fof(f42, plain, ~ ? [X0] : (aSupremumOfIn0(X0, xT, xS) | (! [X1] : ((aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (aElementOf0(X2, xT) => sdtlseqdt0(X2, X1)) & aElementOf0(X1, xS)) => sdtlseqdt0(X0, X1)) & (aUpperBoundOfIn0(X0, xT, xS) | (! [X3] : (aElementOf0(X3, xT) => sdtlseqdt0(X3, X0)) & aElementOf0(X0, xS))) & aElementOf0(X0, xS))), inference(rectify, [], [f32])).
fof(f32, plain, ~ ? [X0] : (aSupremumOfIn0(X0, xT, xS) | (! [X1] : ((aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (aElementOf0(X2, xT) => sdtlseqdt0(X2, X1)) & aElementOf0(X1, xS)) => sdtlseqdt0(X0, X1)) & (aUpperBoundOfIn0(X0, xT, xS) | (! [X1] : (aElementOf0(X1, xT) => sdtlseqdt0(X1, X0)) & aElementOf0(X0, xS))) & aElementOf0(X0, xS))), inference(negated_conjecture, [], [f31])).
fof(f31, plain, ~ ? [X0] : (aSupremumOfIn0(X0, xT, xS) | (! [X1] : ((aUpperBoundOfIn0(X1, xT, xS) & ! [X2] : (aElementOf0(X2, xT) => sdtlseqdt0(X2, X1)) & aElementOf0(X1, xS)) => sdtlseqdt0(X0, X1)) & (aUpperBoundOfIn0(X0, xT, xS) | (! [X1] : (aElementOf0(X1, xT) => sdtlseqdt0(X1, X0)) & aElementOf0(X0, xS))) & aElementOf0(X0, xS))), file('/home/ubuntu/library/tptp/Problems/LAT/LAT388+4.p', m__)).
fof(f268, plain, aSupremumOfIn0(xp, xT, xS), inference(cnf_transformation, [], [f146])).
fof(f146, plain, (aSupremumOfIn0(xp, xT, xS) & ! [X0] : (sdtlseqdt0(xp, X0) | (~ aUpperBoundOfIn0(X0, xT, xS) & ((~ sdtlseqdt0(sK21(X0), X0) & aElementOf0(sK21(X0), xT)) | ~ aElementOf0(X0, xS)))) & aUpperBoundOfIn0(xp, xT, xS) & ! [X2] : (sdtlseqdt0(X2, xp) | ~ aElementOf0(X2, xT)) & aFixedPointOf0(xp, xf) & (xp = sdtlpdtrp0(xf, xp)) & aElementOf0(xp, szDzozmdt0(xf))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK21])], [f77, f145])).
fof(f145, plain, ! [X0] : (? [X1] : (~ sdtlseqdt0(X1, X0) & aElementOf0(X1, xT)) => (~ sdtlseqdt0(sK21(X0), X0) & aElementOf0(sK21(X0), xT))), introduced(choice_axiom, [])).
fof(f77, plain, (aSupremumOfIn0(xp, xT, xS) & ! [X0] : (sdtlseqdt0(xp, X0) | (~ aUpperBoundOfIn0(X0, xT, xS) & (? [X1] : (~ sdtlseqdt0(X1, X0) & aElementOf0(X1, xT)) | ~ aElementOf0(X0, xS)))) & aUpperBoundOfIn0(xp, xT, xS) & ! [X2] : (sdtlseqdt0(X2, xp) | ~ aElementOf0(X2, xT)) & aFixedPointOf0(xp, xf) & (xp = sdtlpdtrp0(xf, xp)) & aElementOf0(xp, szDzozmdt0(xf))), inference(ennf_transformation, [], [f41])).
fof(f41, plain, (aSupremumOfIn0(xp, xT, xS) & ! [X0] : ((aUpperBoundOfIn0(X0, xT, xS) | (! [X1] : (aElementOf0(X1, xT) => sdtlseqdt0(X1, X0)) & aElementOf0(X0, xS))) => sdtlseqdt0(xp, X0)) & aUpperBoundOfIn0(xp, xT, xS) & ! [X2] : (aElementOf0(X2, xT) => sdtlseqdt0(X2, xp)) & aFixedPointOf0(xp, xf) & (xp = sdtlpdtrp0(xf, xp)) & aElementOf0(xp, szDzozmdt0(xf))), inference(rectify, [], [f30])).
fof(f30, plain, (aSupremumOfIn0(xp, xT, xS) & ! [X0] : ((aUpperBoundOfIn0(X0, xT, xS) | (! [X1] : (aElementOf0(X1, xT) => sdtlseqdt0(X1, X0)) & aElementOf0(X0, xS))) => sdtlseqdt0(xp, X0)) & aUpperBoundOfIn0(xp, xT, xS) & ! [X0] : (aElementOf0(X0, xT) => sdtlseqdt0(X0, xp)) & aFixedPointOf0(xp, xf) & (xp = sdtlpdtrp0(xf, xp)) & aElementOf0(xp, szDzozmdt0(xf))), file('/home/ubuntu/library/tptp/Problems/LAT/LAT388+4.p', m__1330)).