fof(f117, plain, $false, inference(avatar_sat_refutation, [], [f66, f90, f116])).
fof(f116, plain, (spl6_1 | ~ spl6_2), inference(avatar_contradiction_clause, [], [f115])).
fof(f115, plain, ($false | (spl6_1 | ~ spl6_2)), inference(subsumption_resolution, [], [f114, f33])).
fof(f33, plain, environment(sK4), inference(cnf_transformation, [], [f24])).
fof(f24, plain, (! [X1] : ((~ greater(growth_rate(efficient_producers, sK5(X1)), growth_rate(first_movers, sK5(X1))) & greater(sK5(X1), X1) & subpopulations(first_movers, efficient_producers, sK4, sK5(X1))) | greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | ~ in_environment(sK4, X1)) & stable(sK4) & environment(sK4)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK4, sK5])], [f11, f23, f22])).
fof(f22, plain, (? [X0] : (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) | greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | ~ in_environment(X0, X1)) & stable(X0) & environment(X0)) => (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater(X2, X1) & subpopulations(first_movers, efficient_producers, sK4, X2)) | greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | ~ in_environment(sK4, X1)) & stable(sK4) & environment(sK4))), introduced(choice_axiom, [])).
fof(f23, plain, ! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater(X2, X1) & subpopulations(first_movers, efficient_producers, sK4, X2)) => (~ greater(growth_rate(efficient_producers, sK5(X1)), growth_rate(first_movers, sK5(X1))) & greater(sK5(X1), X1) & subpopulations(first_movers, efficient_producers, sK4, sK5(X1)))), introduced(choice_axiom, [])).
fof(f11, plain, ? [X0] : (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) | greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | ~ in_environment(X0, X1)) & stable(X0) & environment(X0)), inference(flattening, [], [f10])).
fof(f10, plain, ? [X0] : (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & (greater(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2))) | greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | ~ in_environment(X0, X1)) & (stable(X0) & environment(X0))), inference(ennf_transformation, [], [f4])).
fof(f4, plain, ~ ! [X0] : ((stable(X0) & environment(X0)) => ? [X1] : (! [X2] : ((greater(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2))) & ~ greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) & in_environment(X0, X1))), inference(negated_conjecture, [], [f3])).
fof(f3, plain, ~ ! [X0] : ((stable(X0) & environment(X0)) => ? [X1] : (! [X2] : ((greater(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2))) & ~ greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) & in_environment(X0, X1))), file('/home/ubuntu/library/tptp/Problems/MGT/MGT030+1.p', prove_l12)).
fof(f114, plain, (~ environment(sK4) | (spl6_1 | ~ spl6_2)), inference(subsumption_resolution, [], [f113, f61])).
fof(f61, plain, (~ sP0(sK4) | spl6_1), inference(avatar_component_clause, [], [f60])).
fof(f60, plain, (spl6_1 <=> sP0(sK4)), introduced(avatar_definition, [new_symbols(naming, [spl6_1])])).
fof(f113, plain, (sP0(sK4) | ~ environment(sK4) | (spl6_1 | ~ spl6_2)), inference(resolution, [], [f106, f28])).
fof(f28, plain, ! [X0] : (in_environment(X0, sK2(X0)) | sP0(X0) | ~ environment(X0)), inference(cnf_transformation, [], [f19])).
fof(f19, plain, ! [X0] : ((! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater(X2, sK2(X0)) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & ~ greater(growth_rate(efficient_producers, sK2(X0)), growth_rate(first_movers, sK2(X0))) & in_environment(X0, sK2(X0))) | sP0(X0) | ~ environment(X0)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK2])], [f17, f18])).
fof(f18, plain, ! [X0] : (? [X1] : (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater(X2, X1) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & ~ greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) & in_environment(X0, X1)) => (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater(X2, sK2(X0)) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & ~ greater(growth_rate(efficient_producers, sK2(X0)), growth_rate(first_movers, sK2(X0))) & in_environment(X0, sK2(X0)))), introduced(choice_axiom, [])).
fof(f17, plain, ! [X0] : (? [X1] : (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater(X2, X1) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & ~ greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) & in_environment(X0, X1)) | sP0(X0) | ~ environment(X0)), inference(rectify, [], [f13])).
fof(f13, plain, ! [X0] : (? [X3] : (! [X4] : (greater(growth_rate(efficient_producers, X4), growth_rate(first_movers, X4)) | ~ greater(X4, X3) | ~ subpopulations(first_movers, efficient_producers, X0, X4)) & ~ greater(growth_rate(efficient_producers, X3), growth_rate(first_movers, X3)) & in_environment(X0, X3)) | sP0(X0) | ~ environment(X0)), inference(definition_folding, [], [f7, e12])).
fof(f12, plain, ! [X0] : (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) | ~ in_environment(X0, X1)) | ~ sP0(X0)), inference(usedef, [], [e12])).
fof(e12, plain, ! [X0] : (sP0(X0) <=> ! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) | ~ in_environment(X0, X1))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP0])])).
fof(f7, plain, ! [X0] : (? [X3] : (! [X4] : (greater(growth_rate(efficient_producers, X4), growth_rate(first_movers, X4)) | ~ greater(X4, X3) | ~ subpopulations(first_movers, efficient_producers, X0, X4)) & ~ greater(growth_rate(efficient_producers, X3), growth_rate(first_movers, X3)) & in_environment(X0, X3)) | ! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) | ~ in_environment(X0, X1)) | ~ environment(X0)), inference(flattening, [], [f6])).
fof(f6, plain, ! [X0] : (? [X3] : (! [X4] : (greater(growth_rate(efficient_producers, X4), growth_rate(first_movers, X4)) | (~ greater(X4, X3) | ~ subpopulations(first_movers, efficient_producers, X0, X4))) & ~ greater(growth_rate(efficient_producers, X3), growth_rate(first_movers, X3)) & in_environment(X0, X3)) | (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & (greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2))) | ~ in_environment(X0, X1)) | ~ environment(X0))), inference(ennf_transformation, [], [f5])).
fof(f5, plain, ! [X0] : ((? [X1] : (! [X2] : ((greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2))) & in_environment(X0, X1)) & environment(X0)) => ? [X3] : (! [X4] : ((greater(X4, X3) & subpopulations(first_movers, efficient_producers, X0, X4)) => greater(growth_rate(efficient_producers, X4), growth_rate(first_movers, X4))) & ~ greater(growth_rate(efficient_producers, X3), growth_rate(first_movers, X3)) & in_environment(X0, X3))), inference(rectify, [], [f1])).
fof(f1, plain, ! [X0] : ((? [X1] : (! [X2] : ((greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2))) & in_environment(X0, X1)) & environment(X0)) => ? [X1] : (! [X2] : ((greater(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2))) & ~ greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) & in_environment(X0, X1))), file('/home/ubuntu/library/tptp/Problems/MGT/MGT030+1.p', mp_earliest_time_growth_rate_exceeds)).
fof(f106, plain, (~ in_environment(sK4, sK2(sK4)) | (spl6_1 | ~ spl6_2)), inference(subsumption_resolution, [], [f105, f33])).
fof(f105, plain, (~ in_environment(sK4, sK2(sK4)) | ~ environment(sK4) | (spl6_1 | ~ spl6_2)), inference(subsumption_resolution, [], [f104, f61])).
fof(f104, plain, (sP0(sK4) | ~ in_environment(sK4, sK2(sK4)) | ~ environment(sK4) | ~ spl6_2), inference(duplicate_literal_removal, [], [f103])).
fof(f103, plain, (sP0(sK4) | ~ in_environment(sK4, sK2(sK4)) | ~ environment(sK4) | ~ in_environment(sK4, sK2(sK4)) | sP0(sK4) | ~ environment(sK4) | ~ spl6_2), inference(resolution, [], [f102, f38])).
fof(f38, plain, ! [X0] : (greater(sK5(sK2(X0)), sK2(X0)) | ~ in_environment(sK4, sK2(X0)) | sP0(X0) | ~ environment(X0)), inference(resolution, [], [f36, f29])).
fof(f29, plain, ! [X0] : (~ greater(growth_rate(efficient_producers, sK2(X0)), growth_rate(first_movers, sK2(X0))) | sP0(X0) | ~ environment(X0)), inference(cnf_transformation, [], [f19])).
fof(f36, plain, ! [X1] : (greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | greater(sK5(X1), X1) | ~ in_environment(sK4, X1)), inference(cnf_transformation, [], [f24])).
fof(f102, plain, (! [X0] : (~ greater(sK5(sK2(X0)), sK2(sK4)) | sP0(X0) | ~ in_environment(sK4, sK2(X0)) | ~ environment(X0)) | ~ spl6_2), inference(subsumption_resolution, [], [f101, f29])).
fof(f101, plain, (! [X0] : (~ environment(X0) | sP0(X0) | ~ in_environment(sK4, sK2(X0)) | ~ greater(sK5(sK2(X0)), sK2(sK4)) | greater(growth_rate(efficient_producers, sK2(X0)), growth_rate(first_movers, sK2(X0)))) | ~ spl6_2), inference(duplicate_literal_removal, [], [f100])).
fof(f100, plain, (! [X0] : (~ environment(X0) | sP0(X0) | ~ in_environment(sK4, sK2(X0)) | ~ greater(sK5(sK2(X0)), sK2(sK4)) | greater(growth_rate(efficient_producers, sK2(X0)), growth_rate(first_movers, sK2(X0))) | ~ in_environment(sK4, sK2(X0))) | ~ spl6_2), inference(resolution, [], [f65, f37])).
fof(f37, plain, ! [X1] : (~ greater(growth_rate(efficient_producers, sK5(X1)), growth_rate(first_movers, sK5(X1))) | greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | ~ in_environment(sK4, X1)), inference(cnf_transformation, [], [f24])).
fof(f65, plain, (! [X2] : (greater(growth_rate(efficient_producers, sK5(sK2(X2))), growth_rate(first_movers, sK5(sK2(X2)))) | ~ environment(X2) | sP0(X2) | ~ in_environment(sK4, sK2(X2)) | ~ greater(sK5(sK2(X2)), sK2(sK4))) | ~ spl6_2), inference(avatar_component_clause, [], [f64])).
fof(f64, plain, (spl6_2 <=> ! [X2] : (~ greater(sK5(sK2(X2)), sK2(sK4)) | ~ environment(X2) | sP0(X2) | ~ in_environment(sK4, sK2(X2)) | greater(growth_rate(efficient_producers, sK5(sK2(X2))), growth_rate(first_movers, sK5(sK2(X2)))))), introduced(avatar_definition, [new_symbols(naming, [spl6_2])])).
fof(f90, plain, ~ spl6_1, inference(avatar_contradiction_clause, [], [f89])).
fof(f89, plain, ($false | ~ spl6_1), inference(subsumption_resolution, [], [f88, f34])).
fof(f34, plain, stable(sK4), inference(cnf_transformation, [], [f24])).
fof(f88, plain, (~ stable(sK4) | ~ spl6_1), inference(subsumption_resolution, [], [f87, f33])).
fof(f87, plain, (~ environment(sK4) | ~ stable(sK4) | ~ spl6_1), inference(resolution, [], [f62, f54])).
fof(f54, plain, ! [X0] : (~ sP0(X0) | ~ environment(X0) | ~ stable(X0)), inference(subsumption_resolution, [], [f53, f31])).
fof(f31, plain, ! [X0] : (in_environment(X0, sK3(X0)) | ~ stable(X0) | ~ environment(X0)), inference(cnf_transformation, [], [f21])).
fof(f21, plain, ! [X0] : ((! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater_or_equal(X2, sK3(X0)) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & in_environment(X0, sK3(X0))) | ~ stable(X0) | ~ environment(X0)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK3])], [f9, f20])).
fof(f20, plain, ! [X0] : (? [X1] : (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater_or_equal(X2, X1) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & in_environment(X0, X1)) => (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater_or_equal(X2, sK3(X0)) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & in_environment(X0, sK3(X0)))), introduced(choice_axiom, [])).
fof(f9, plain, ! [X0] : (? [X1] : (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ greater_or_equal(X2, X1) | ~ subpopulations(first_movers, efficient_producers, X0, X2)) & in_environment(X0, X1)) | ~ stable(X0) | ~ environment(X0)), inference(flattening, [], [f8])).
fof(f8, plain, ! [X0] : (? [X1] : (! [X2] : (greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | (~ greater_or_equal(X2, X1) | ~ subpopulations(first_movers, efficient_producers, X0, X2))) & in_environment(X0, X1)) | (~ stable(X0) | ~ environment(X0))), inference(ennf_transformation, [], [f2])).
fof(f2, plain, ! [X0] : ((stable(X0) & environment(X0)) => ? [X1] : (! [X2] : ((greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2))) & in_environment(X0, X1))), file('/home/ubuntu/library/tptp/Problems/MGT/MGT030+1.p', l1)).
fof(f53, plain, ! [X0] : (~ stable(X0) | ~ environment(X0) | ~ in_environment(X0, sK3(X0)) | ~ sP0(X0)), inference(duplicate_literal_removal, [], [f52])).
fof(f52, plain, ! [X0] : (~ stable(X0) | ~ environment(X0) | ~ in_environment(X0, sK3(X0)) | ~ sP0(X0) | ~ in_environment(X0, sK3(X0)) | ~ sP0(X0)), inference(resolution, [], [f47, f26])).
fof(f26, plain, ! [X0, X1] : (greater_or_equal(sK1(X0, X1), X1) | ~ in_environment(X0, X1) | ~ sP0(X0)), inference(cnf_transformation, [], [f16])).
fof(f16, plain, ! [X0] : (! [X1] : ((~ greater(growth_rate(efficient_producers, sK1(X0, X1)), growth_rate(first_movers, sK1(X0, X1))) & greater_or_equal(sK1(X0, X1), X1) & subpopulations(first_movers, efficient_producers, X0, sK1(X0, X1))) | ~ in_environment(X0, X1)) | ~ sP0(X0)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK1])], [f14, f15])).
fof(f15, plain, ! [X1, X0] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) => (~ greater(growth_rate(efficient_producers, sK1(X0, X1)), growth_rate(first_movers, sK1(X0, X1))) & greater_or_equal(sK1(X0, X1), X1) & subpopulations(first_movers, efficient_producers, X0, sK1(X0, X1)))), introduced(choice_axiom, [])).
fof(f14, plain, ! [X0] : (! [X1] : (? [X2] : (~ greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) & greater_or_equal(X2, X1) & subpopulations(first_movers, efficient_producers, X0, X2)) | ~ in_environment(X0, X1)) | ~ sP0(X0)), inference(nnf_transformation, [], [f12])).
fof(f47, plain, ! [X0, X1] : (~ greater_or_equal(sK1(X0, X1), sK3(X0)) | ~ stable(X0) | ~ environment(X0) | ~ in_environment(X0, X1) | ~ sP0(X0)), inference(subsumption_resolution, [], [f44, f27])).
fof(f27, plain, ! [X0, X1] : (~ greater(growth_rate(efficient_producers, sK1(X0, X1)), growth_rate(first_movers, sK1(X0, X1))) | ~ in_environment(X0, X1) | ~ sP0(X0)), inference(cnf_transformation, [], [f16])).
fof(f44, plain, ! [X0, X1] : (~ greater_or_equal(sK1(X0, X1), sK3(X0)) | greater(growth_rate(efficient_producers, sK1(X0, X1)), growth_rate(first_movers, sK1(X0, X1))) | ~ stable(X0) | ~ environment(X0) | ~ in_environment(X0, X1) | ~ sP0(X0)), inference(resolution, [], [f32, f25])).
fof(f25, plain, ! [X0, X1] : (subpopulations(first_movers, efficient_producers, X0, sK1(X0, X1)) | ~ in_environment(X0, X1) | ~ sP0(X0)), inference(cnf_transformation, [], [f16])).
fof(f32, plain, ! [X2, X0] : (~ subpopulations(first_movers, efficient_producers, X0, X2) | ~ greater_or_equal(X2, sK3(X0)) | greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | ~ stable(X0) | ~ environment(X0)), inference(cnf_transformation, [], [f21])).
fof(f62, plain, (sP0(sK4) | ~ spl6_1), inference(avatar_component_clause, [], [f60])).
fof(f66, plain, (spl6_1 | spl6_2), inference(avatar_split_clause, [], [f58, f64, f60])).
fof(f58, plain, ! [X2] : (~ greater(sK5(sK2(X2)), sK2(sK4)) | greater(growth_rate(efficient_producers, sK5(sK2(X2))), growth_rate(first_movers, sK5(sK2(X2)))) | sP0(sK4) | ~ in_environment(sK4, sK2(X2)) | sP0(X2) | ~ environment(X2)), inference(subsumption_resolution, [], [f56, f33])).
fof(f56, plain, ! [X2] : (~ greater(sK5(sK2(X2)), sK2(sK4)) | greater(growth_rate(efficient_producers, sK5(sK2(X2))), growth_rate(first_movers, sK5(sK2(X2)))) | sP0(sK4) | ~ environment(sK4) | ~ in_environment(sK4, sK2(X2)) | sP0(X2) | ~ environment(X2)), inference(resolution, [], [f30, f39])).
fof(f39, plain, ! [X0] : (subpopulations(first_movers, efficient_producers, sK4, sK5(sK2(X0))) | ~ in_environment(sK4, sK2(X0)) | sP0(X0) | ~ environment(X0)), inference(resolution, [], [f35, f29])).
fof(f35, plain, ! [X1] : (greater(growth_rate(efficient_producers, X1), growth_rate(first_movers, X1)) | subpopulations(first_movers, efficient_producers, sK4, sK5(X1)) | ~ in_environment(sK4, X1)), inference(cnf_transformation, [], [f24])).
fof(f30, plain, ! [X2, X0] : (~ subpopulations(first_movers, efficient_producers, X0, X2) | ~ greater(X2, sK2(X0)) | greater(growth_rate(efficient_producers, X2), growth_rate(first_movers, X2)) | sP0(X0) | ~ environment(X0)), inference(cnf_transformation, [], [f19])).