fof(f10574, plain, $false, inference(subsumption_resolution, [], [f10566, f577])).
fof(f577, plain, aElementOf0(xi, szNzAzT0), inference(cnf_transformation, [], [f85])).
fof(f85, plain, aElementOf0(xi, szNzAzT0), file('/home/ubuntu/library/tptp/Problems/NUM/NUM582+3.p', m__3989)).
fof(f10566, plain, ~ aElementOf0(xi, szNzAzT0), inference(resolution, [], [f4094, f600])).
fof(f600, plain, ~ aSubsetOf0(sdtlpdtrp0(xN, xi), xS), inference(cnf_transformation, [], [f347])).
fof(f347, plain, (~ aSubsetOf0(sdtlpdtrp0(xN, xi), xS) & (~ aElementOf0(sK41, xS) & aElementOf0(sK41, sdtlpdtrp0(xN, xi)))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK41])], [f216, f346])).
fof(f346, plain, (? [X0] : (~ aElementOf0(X0, xS) & aElementOf0(X0, sdtlpdtrp0(xN, xi))) => (~ aElementOf0(sK41, xS) & aElementOf0(sK41, sdtlpdtrp0(xN, xi)))), introduced(choice_axiom, [])).
fof(f216, plain, (~ aSubsetOf0(sdtlpdtrp0(xN, xi), xS) & ? [X0] : (~ aElementOf0(X0, xS) & aElementOf0(X0, sdtlpdtrp0(xN, xi)))), inference(ennf_transformation, [], [f89])).
fof(f89, plain, ~ (aSubsetOf0(sdtlpdtrp0(xN, xi), xS) | ! [X0] : (aElementOf0(X0, sdtlpdtrp0(xN, xi)) => aElementOf0(X0, xS))), inference(negated_conjecture, [], [f88])).
fof(f88, plain, ~ (aSubsetOf0(sdtlpdtrp0(xN, xi), xS) | ! [X0] : (aElementOf0(X0, sdtlpdtrp0(xN, xi)) => aElementOf0(X0, xS))), file('/home/ubuntu/library/tptp/Problems/NUM/NUM582+3.p', m__)).
fof(f4094, plain, ! [X0] : (aSubsetOf0(sdtlpdtrp0(xN, X0), xS) | ~ aElementOf0(X0, szNzAzT0)), inference(subsumption_resolution, [], [f4093, f402])).
fof(f402, plain, ! [X0] : (~ aElementOf0(X0, szNzAzT0) | sdtlseqdt0(sz00, X0)), inference(cnf_transformation, [], [f138])).
fof(f138, plain, ! [X0] : (sdtlseqdt0(sz00, X0) | ~ aElementOf0(X0, szNzAzT0)), inference(ennf_transformation, [], [f30])).
fof(f30, plain, ! [X0] : (aElementOf0(X0, szNzAzT0) => sdtlseqdt0(sz00, X0)), file('/home/ubuntu/library/tptp/Problems/NUM/NUM582+3.p', mZeroLess)).
fof(f4093, plain, ! [X0] : (aSubsetOf0(sdtlpdtrp0(xN, X0), xS) | ~ sdtlseqdt0(sz00, X0) | ~ aElementOf0(X0, szNzAzT0)), inference(subsumption_resolution, [], [f4089, f395])).
fof(f395, plain, aElementOf0(sz00, szNzAzT0), inference(cnf_transformation, [], [f24])).
fof(f24, plain, aElementOf0(sz00, szNzAzT0), file('/home/ubuntu/library/tptp/Problems/NUM/NUM582+3.p', mZeroNum)).
fof(f4089, plain, ! [X0] : (aSubsetOf0(sdtlpdtrp0(xN, X0), xS) | ~ sdtlseqdt0(sz00, X0) | ~ aElementOf0(sz00, szNzAzT0) | ~ aElementOf0(X0, szNzAzT0)), inference(superposition, [], [f571, f562])).
fof(f562, plain, (xS = sdtlpdtrp0(xN, sz00)), inference(cnf_transformation, [], [f338])).
fof(f338, plain, (! [X0] : (sP9(X0) | ~ isCountable0(sdtlpdtrp0(xN, X0)) | (~ aSubsetOf0(sdtlpdtrp0(xN, X0), szNzAzT0) & ((~ aElementOf0(sK39(X0), szNzAzT0) & aElementOf0(sK39(X0), sdtlpdtrp0(xN, X0))) | ~ aSet0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X0, szNzAzT0)) & (xS = sdtlpdtrp0(xN, sz00)) & (szNzAzT0 = szDzozmdt0(xN)) & aFunction0(xN)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK39])], [f230, f337])).
fof(f337, plain, ! [X0] : (? [X1] : (~ aElementOf0(X1, szNzAzT0) & aElementOf0(X1, sdtlpdtrp0(xN, X0))) => (~ aElementOf0(sK39(X0), szNzAzT0) & aElementOf0(sK39(X0), sdtlpdtrp0(xN, X0)))), introduced(choice_axiom, [])).
fof(f230, plain, (! [X0] : (sP9(X0) | ~ isCountable0(sdtlpdtrp0(xN, X0)) | (~ aSubsetOf0(sdtlpdtrp0(xN, X0), szNzAzT0) & (? [X1] : (~ aElementOf0(X1, szNzAzT0) & aElementOf0(X1, sdtlpdtrp0(xN, X0))) | ~ aSet0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X0, szNzAzT0)) & (xS = sdtlpdtrp0(xN, sz00)) & (szNzAzT0 = szDzozmdt0(xN)) & aFunction0(xN)), inference(definition_folding, [], [f208, e229, e228])).
fof(f228, plain, ! [X0] : (! [X3] : (aElementOf0(X3, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) <=> (~ (szmzizndt0(sdtlpdtrp0(xN, X0)) = X3) & aElementOf0(X3, sdtlpdtrp0(xN, X0)) & aElement0(X3))) | ~ sP8(X0)), inference(usedef, [], [e228])).
fof(e228, plain, ! [X0] : (sP8(X0) <=> ! [X3] : (aElementOf0(X3, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) <=> (~ (szmzizndt0(sdtlpdtrp0(xN, X0)) = X3) & aElementOf0(X3, sdtlpdtrp0(xN, X0)) & aElement0(X3)))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP8])])).
fof(f229, plain, ! [X0] : ((isCountable0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & aSubsetOf0(sdtlpdtrp0(xN, szszuzczcdt0(X0)), sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X2] : (aElementOf0(X2, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X2, sdtlpdtrp0(xN, szszuzczcdt0(X0)))) & aSet0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & sP8(X0) & aSet0(sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X4] : (sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN, X0)), X4) | ~ aElementOf0(X4, sdtlpdtrp0(xN, X0))) & aElementOf0(szmzizndt0(sdtlpdtrp0(xN, X0)), sdtlpdtrp0(xN, X0))) | ~ sP9(X0)), inference(usedef, [], [e229])).
fof(e229, plain, ! [X0] : (sP9(X0) <=> (isCountable0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & aSubsetOf0(sdtlpdtrp0(xN, szszuzczcdt0(X0)), sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X2] : (aElementOf0(X2, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X2, sdtlpdtrp0(xN, szszuzczcdt0(X0)))) & aSet0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & sP8(X0) & aSet0(sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X4] : (sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN, X0)), X4) | ~ aElementOf0(X4, sdtlpdtrp0(xN, X0))) & aElementOf0(szmzizndt0(sdtlpdtrp0(xN, X0)), sdtlpdtrp0(xN, X0)))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP9])])).
fof(f208, plain, (! [X0] : ((isCountable0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & aSubsetOf0(sdtlpdtrp0(xN, szszuzczcdt0(X0)), sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X2] : (aElementOf0(X2, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X2, sdtlpdtrp0(xN, szszuzczcdt0(X0)))) & aSet0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & ! [X3] : (aElementOf0(X3, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) <=> (~ (szmzizndt0(sdtlpdtrp0(xN, X0)) = X3) & aElementOf0(X3, sdtlpdtrp0(xN, X0)) & aElement0(X3))) & aSet0(sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X4] : (sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN, X0)), X4) | ~ aElementOf0(X4, sdtlpdtrp0(xN, X0))) & aElementOf0(szmzizndt0(sdtlpdtrp0(xN, X0)), sdtlpdtrp0(xN, X0))) | ~ isCountable0(sdtlpdtrp0(xN, X0)) | (~ aSubsetOf0(sdtlpdtrp0(xN, X0), szNzAzT0) & (? [X1] : (~ aElementOf0(X1, szNzAzT0) & aElementOf0(X1, sdtlpdtrp0(xN, X0))) | ~ aSet0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X0, szNzAzT0)) & (xS = sdtlpdtrp0(xN, sz00)) & (szNzAzT0 = szDzozmdt0(xN)) & aFunction0(xN)), inference(flattening, [], [f207])).
fof(f207, plain, (! [X0] : (((isCountable0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & aSubsetOf0(sdtlpdtrp0(xN, szszuzczcdt0(X0)), sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X2] : (aElementOf0(X2, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) | ~ aElementOf0(X2, sdtlpdtrp0(xN, szszuzczcdt0(X0)))) & aSet0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & ! [X3] : (aElementOf0(X3, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) <=> (~ (szmzizndt0(sdtlpdtrp0(xN, X0)) = X3) & aElementOf0(X3, sdtlpdtrp0(xN, X0)) & aElement0(X3))) & aSet0(sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X4] : (sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN, X0)), X4) | ~ aElementOf0(X4, sdtlpdtrp0(xN, X0))) & aElementOf0(szmzizndt0(sdtlpdtrp0(xN, X0)), sdtlpdtrp0(xN, X0))) | (~ isCountable0(sdtlpdtrp0(xN, X0)) | (~ aSubsetOf0(sdtlpdtrp0(xN, X0), szNzAzT0) & (? [X1] : (~ aElementOf0(X1, szNzAzT0) & aElementOf0(X1, sdtlpdtrp0(xN, X0))) | ~ aSet0(sdtlpdtrp0(xN, X0)))))) | ~ aElementOf0(X0, szNzAzT0)) & (xS = sdtlpdtrp0(xN, sz00)) & (szNzAzT0 = szDzozmdt0(xN)) & aFunction0(xN)), inference(ennf_transformation, [], [f99])).
fof(f99, plain, (! [X0] : (aElementOf0(X0, szNzAzT0) => ((isCountable0(sdtlpdtrp0(xN, X0)) & (aSubsetOf0(sdtlpdtrp0(xN, X0), szNzAzT0) | (! [X1] : (aElementOf0(X1, sdtlpdtrp0(xN, X0)) => aElementOf0(X1, szNzAzT0)) & aSet0(sdtlpdtrp0(xN, X0))))) => (isCountable0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & aSubsetOf0(sdtlpdtrp0(xN, szszuzczcdt0(X0)), sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X2] : (aElementOf0(X2, sdtlpdtrp0(xN, szszuzczcdt0(X0))) => aElementOf0(X2, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0))))) & aSet0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & ! [X3] : (aElementOf0(X3, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) <=> (~ (szmzizndt0(sdtlpdtrp0(xN, X0)) = X3) & aElementOf0(X3, sdtlpdtrp0(xN, X0)) & aElement0(X3))) & aSet0(sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X4] : (aElementOf0(X4, sdtlpdtrp0(xN, X0)) => sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN, X0)), X4)) & aElementOf0(szmzizndt0(sdtlpdtrp0(xN, X0)), sdtlpdtrp0(xN, X0))))) & (xS = sdtlpdtrp0(xN, sz00)) & (szNzAzT0 = szDzozmdt0(xN)) & aFunction0(xN)), inference(rectify, [], [f81])).
fof(f81, plain, (! [X0] : (aElementOf0(X0, szNzAzT0) => ((isCountable0(sdtlpdtrp0(xN, X0)) & (aSubsetOf0(sdtlpdtrp0(xN, X0), szNzAzT0) | (! [X1] : (aElementOf0(X1, sdtlpdtrp0(xN, X0)) => aElementOf0(X1, szNzAzT0)) & aSet0(sdtlpdtrp0(xN, X0))))) => (isCountable0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & aSubsetOf0(sdtlpdtrp0(xN, szszuzczcdt0(X0)), sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X1] : (aElementOf0(X1, sdtlpdtrp0(xN, szszuzczcdt0(X0))) => aElementOf0(X1, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0))))) & aSet0(sdtlpdtrp0(xN, szszuzczcdt0(X0))) & ! [X1] : (aElementOf0(X1, sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) <=> (~ (szmzizndt0(sdtlpdtrp0(xN, X0)) = X1) & aElementOf0(X1, sdtlpdtrp0(xN, X0)) & aElement0(X1))) & aSet0(sdtmndt0(sdtlpdtrp0(xN, X0), szmzizndt0(sdtlpdtrp0(xN, X0)))) & ! [X1] : (aElementOf0(X1, sdtlpdtrp0(xN, X0)) => sdtlseqdt0(szmzizndt0(sdtlpdtrp0(xN, X0)), X1)) & aElementOf0(szmzizndt0(sdtlpdtrp0(xN, X0)), sdtlpdtrp0(xN, X0))))) & (xS = sdtlpdtrp0(xN, sz00)) & (szNzAzT0 = szDzozmdt0(xN)) & aFunction0(xN)), file('/home/ubuntu/library/tptp/Problems/NUM/NUM582+3.p', m__3623)).
fof(f571, plain, ! [X0, X1] : (aSubsetOf0(sdtlpdtrp0(xN, X0), sdtlpdtrp0(xN, X1)) | ~ sdtlseqdt0(X1, X0) | ~ aElementOf0(X1, szNzAzT0) | ~ aElementOf0(X0, szNzAzT0)), inference(cnf_transformation, [], [f211])).
fof(f211, plain, ! [X0, X1] : ((aSubsetOf0(sdtlpdtrp0(xN, X0), sdtlpdtrp0(xN, X1)) & ! [X2] : (aElementOf0(X2, sdtlpdtrp0(xN, X1)) | ~ aElementOf0(X2, sdtlpdtrp0(xN, X0)))) | ~ sdtlseqdt0(X1, X0) | ~ aElementOf0(X1, szNzAzT0) | ~ aElementOf0(X0, szNzAzT0)), inference(flattening, [], [f210])).
fof(f210, plain, ! [X0, X1] : (((aSubsetOf0(sdtlpdtrp0(xN, X0), sdtlpdtrp0(xN, X1)) & ! [X2] : (aElementOf0(X2, sdtlpdtrp0(xN, X1)) | ~ aElementOf0(X2, sdtlpdtrp0(xN, X0)))) | ~ sdtlseqdt0(X1, X0)) | (~ aElementOf0(X1, szNzAzT0) | ~ aElementOf0(X0, szNzAzT0))), inference(ennf_transformation, [], [f83])).
fof(f83, plain, ! [X0, X1] : ((aElementOf0(X1, szNzAzT0) & aElementOf0(X0, szNzAzT0)) => (sdtlseqdt0(X1, X0) => (aSubsetOf0(sdtlpdtrp0(xN, X0), sdtlpdtrp0(xN, X1)) & ! [X2] : (aElementOf0(X2, sdtlpdtrp0(xN, X0)) => aElementOf0(X2, sdtlpdtrp0(xN, X1)))))), file('/home/ubuntu/library/tptp/Problems/NUM/NUM582+3.p', m__3754)).