fof(f1022, plain, $false, inference(subsumption_resolution, [], [f152, f1018])).
fof(f1018, plain, (apply(relation_rng_restriction(sK13, sK15), sK14) = apply(sK15, sK14)), inference(subsumption_resolution, [], [f1017, f150])).
fof(f150, plain, function(sK15), inference(cnf_transformation, [], [f95])).
fof(f95, plain, (~ (apply(relation_rng_restriction(sK13, sK15), sK14) = apply(sK15, sK14)) & in(sK14, relation_dom(relation_rng_restriction(sK13, sK15))) & function(sK15) & relation(sK15)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK13, sK14, sK15])], [f66, f94])).
fof(f94, plain, (? [X0, X1, X2] : (~ (apply(relation_rng_restriction(X0, X2), X1) = apply(X2, X1)) & in(X1, relation_dom(relation_rng_restriction(X0, X2))) & function(X2) & relation(X2)) => (~ (apply(relation_rng_restriction(sK13, sK15), sK14) = apply(sK15, sK14)) & in(sK14, relation_dom(relation_rng_restriction(sK13, sK15))) & function(sK15) & relation(sK15))), introduced(choice_axiom, [])).
fof(f66, plain, ? [X0, X1, X2] : (~ (apply(relation_rng_restriction(X0, X2), X1) = apply(X2, X1)) & in(X1, relation_dom(relation_rng_restriction(X0, X2))) & function(X2) & relation(X2)), inference(flattening, [], [f65])).
fof(f65, plain, ? [X0, X1, X2] : ((~ (apply(relation_rng_restriction(X0, X2), X1) = apply(X2, X1)) & in(X1, relation_dom(relation_rng_restriction(X0, X2)))) & (function(X2) & relation(X2))), inference(ennf_transformation, [], [f34])).
fof(f34, plain, ~ ! [X0, X1, X2] : ((function(X2) & relation(X2)) => (in(X1, relation_dom(relation_rng_restriction(X0, X2))) => (apply(relation_rng_restriction(X0, X2), X1) = apply(X2, X1)))), inference(negated_conjecture, [], [f33])).
fof(f33, plain, ~ ! [X0, X1, X2] : ((function(X2) & relation(X2)) => (in(X1, relation_dom(relation_rng_restriction(X0, X2))) => (apply(relation_rng_restriction(X0, X2), X1) = apply(X2, X1)))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU045+1.p', t87_funct_1)).
fof(f1017, plain, (~ function(sK15) | (apply(relation_rng_restriction(sK13, sK15), sK14) = apply(sK15, sK14))), inference(subsumption_resolution, [], [f997, f149])).
fof(f149, plain, relation(sK15), inference(cnf_transformation, [], [f95])).
fof(f997, plain, (~ relation(sK15) | ~ function(sK15) | (apply(relation_rng_restriction(sK13, sK15), sK14) = apply(sK15, sK14))), inference(resolution, [], [f343, f151])).
fof(f151, plain, in(sK14, relation_dom(relation_rng_restriction(sK13, sK15))), inference(cnf_transformation, [], [f95])).
fof(f343, plain, ! [X2, X0, X1] : (~ in(X1, relation_dom(relation_rng_restriction(X2, X0))) | ~ relation(X0) | ~ function(X0) | (apply(X0, X1) = apply(relation_rng_restriction(X2, X0), X1))), inference(resolution, [], [f252, f158])).
fof(f158, plain, ! [X2, X0, X5, X1] : (~ sP0(X0, X1, X2) | ~ in(X5, relation_dom(X0)) | (apply(X1, X5) = apply(X0, X5))), inference(cnf_transformation, [], [f103])).
fof(f103, plain, ! [X0, X1, X2] : ((sP0(X0, X1, X2) | (~ (apply(X1, sK16(X0, X1)) = apply(X0, sK16(X0, X1))) & in(sK16(X0, X1), relation_dom(X0))) | ((~ in(apply(X1, sK17(X0, X1, X2)), X2) | ~ in(sK17(X0, X1, X2), relation_dom(X1)) | ~ in(sK17(X0, X1, X2), relation_dom(X0))) & ((in(apply(X1, sK17(X0, X1, X2)), X2) & in(sK17(X0, X1, X2), relation_dom(X1))) | in(sK17(X0, X1, X2), relation_dom(X0))))) & ((! [X5] : ((apply(X1, X5) = apply(X0, X5)) | ~ in(X5, relation_dom(X0))) & ! [X6] : ((in(X6, relation_dom(X0)) | ~ in(apply(X1, X6), X2) | ~ in(X6, relation_dom(X1))) & ((in(apply(X1, X6), X2) & in(X6, relation_dom(X1))) | ~ in(X6, relation_dom(X0))))) | ~ sP0(X0, X1, X2))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK16, sK17])], [f100, f102, f101])).
fof(f101, plain, ! [X1, X0] : (? [X3] : (~ (apply(X1, X3) = apply(X0, X3)) & in(X3, relation_dom(X0))) => (~ (apply(X1, sK16(X0, X1)) = apply(X0, sK16(X0, X1))) & in(sK16(X0, X1), relation_dom(X0)))), introduced(choice_axiom, [])).
fof(f102, plain, ! [X2, X1, X0] : (? [X4] : ((~ in(apply(X1, X4), X2) | ~ in(X4, relation_dom(X1)) | ~ in(X4, relation_dom(X0))) & ((in(apply(X1, X4), X2) & in(X4, relation_dom(X1))) | in(X4, relation_dom(X0)))) => ((~ in(apply(X1, sK17(X0, X1, X2)), X2) | ~ in(sK17(X0, X1, X2), relation_dom(X1)) | ~ in(sK17(X0, X1, X2), relation_dom(X0))) & ((in(apply(X1, sK17(X0, X1, X2)), X2) & in(sK17(X0, X1, X2), relation_dom(X1))) | in(sK17(X0, X1, X2), relation_dom(X0))))), introduced(choice_axiom, [])).
fof(f100, plain, ! [X0, X1, X2] : ((sP0(X0, X1, X2) | ? [X3] : (~ (apply(X1, X3) = apply(X0, X3)) & in(X3, relation_dom(X0))) | ? [X4] : ((~ in(apply(X1, X4), X2) | ~ in(X4, relation_dom(X1)) | ~ in(X4, relation_dom(X0))) & ((in(apply(X1, X4), X2) & in(X4, relation_dom(X1))) | in(X4, relation_dom(X0))))) & ((! [X5] : ((apply(X1, X5) = apply(X0, X5)) | ~ in(X5, relation_dom(X0))) & ! [X6] : ((in(X6, relation_dom(X0)) | ~ in(apply(X1, X6), X2) | ~ in(X6, relation_dom(X1))) & ((in(apply(X1, X6), X2) & in(X6, relation_dom(X1))) | ~ in(X6, relation_dom(X0))))) | ~ sP0(X0, X1, X2))), inference(rectify, [], [f99])).
fof(f99, plain, ! [X1, X2, X0] : ((sP0(X1, X2, X0) | ? [X3] : (~ (apply(X2, X3) = apply(X1, X3)) & in(X3, relation_dom(X1))) | ? [X4] : ((~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2)) | ~ in(X4, relation_dom(X1))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | in(X4, relation_dom(X1))))) & ((! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : ((in(X4, relation_dom(X1)) | ~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | ~ in(X4, relation_dom(X1))))) | ~ sP0(X1, X2, X0))), inference(flattening, [], [f98])).
fof(f98, plain, ! [X1, X2, X0] : ((sP0(X1, X2, X0) | (? [X3] : (~ (apply(X2, X3) = apply(X1, X3)) & in(X3, relation_dom(X1))) | ? [X4] : (((~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2))) | ~ in(X4, relation_dom(X1))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | in(X4, relation_dom(X1)))))) & ((! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : ((in(X4, relation_dom(X1)) | (~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2)))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | ~ in(X4, relation_dom(X1))))) | ~ sP0(X1, X2, X0))), inference(nnf_transformation, [], [f69])).
fof(f69, plain, ! [X1, X2, X0] : (sP0(X1, X2, X0) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))), inference(usedef, [], [e69])).
fof(e69, plain, ! [X1, X2, X0] : (sP0(X1, X2, X0) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP0])])).
fof(f252, plain, ! [X0, X1] : (sP0(relation_rng_restriction(X0, X1), X1, X0) | ~ function(X1) | ~ relation(X1)), inference(subsumption_resolution, [], [f251, f126])).
fof(f126, plain, ! [X0, X1] : (relation(relation_rng_restriction(X0, X1)) | ~ relation(X1)), inference(cnf_transformation, [], [f59])).
fof(f59, plain, ! [X0, X1] : (relation(relation_rng_restriction(X0, X1)) | ~ relation(X1)), inference(ennf_transformation, [], [f19])).
fof(f19, plain, ! [X0, X1] : (relation(X1) => relation(relation_rng_restriction(X0, X1))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU045+1.p', dt_k8_relat_1)).
fof(f251, plain, ! [X0, X1] : (sP0(relation_rng_restriction(X0, X1), X1, X0) | ~ function(X1) | ~ relation(X1) | ~ relation(relation_rng_restriction(X0, X1))), inference(subsumption_resolution, [], [f250, f128])).
fof(f128, plain, ! [X0, X1] : (function(relation_rng_restriction(X0, X1)) | ~ function(X1) | ~ relation(X1)), inference(cnf_transformation, [], [f61])).
fof(f61, plain, ! [X0, X1] : ((function(relation_rng_restriction(X0, X1)) & relation(relation_rng_restriction(X0, X1))) | ~ function(X1) | ~ relation(X1)), inference(flattening, [], [f60])).
fof(f60, plain, ! [X0, X1] : ((function(relation_rng_restriction(X0, X1)) & relation(relation_rng_restriction(X0, X1))) | (~ function(X1) | ~ relation(X1))), inference(ennf_transformation, [], [f20])).
fof(f20, plain, ! [X0, X1] : ((function(X1) & relation(X1)) => (function(relation_rng_restriction(X0, X1)) & relation(relation_rng_restriction(X0, X1)))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU045+1.p', fc5_funct_1)).
fof(f250, plain, ! [X0, X1] : (sP0(relation_rng_restriction(X0, X1), X1, X0) | ~ function(X1) | ~ relation(X1) | ~ function(relation_rng_restriction(X0, X1)) | ~ relation(relation_rng_restriction(X0, X1))), inference(resolution, [], [f166, f165])).
fof(f165, plain, ! [X2, X0, X1] : (sP1(X0, X2, X1) | ~ function(X2) | ~ relation(X2) | ~ function(X1) | ~ relation(X1)), inference(cnf_transformation, [], [f71])).
fof(f71, plain, ! [X0, X1] : (! [X2] : (sP1(X0, X2, X1) | ~ function(X2) | ~ relation(X2)) | ~ function(X1) | ~ relation(X1)), inference(definition_folding, [], [f68, e70, e69])).
fof(f70, plain, ! [X0, X2, X1] : (((relation_rng_restriction(X0, X2) = X1) <=> sP0(X1, X2, X0)) | ~ sP1(X0, X2, X1)), inference(usedef, [], [e70])).
fof(e70, plain, ! [X0, X2, X1] : (sP1(X0, X2, X1) <=> ((relation_rng_restriction(X0, X2) = X1) <=> sP0(X1, X2, X0))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP1])])).
fof(f68, plain, ! [X0, X1] : (! [X2] : (((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))) | ~ function(X2) | ~ relation(X2)) | ~ function(X1) | ~ relation(X1)), inference(flattening, [], [f67])).
fof(f67, plain, ! [X0, X1] : (! [X2] : (((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))) | (~ function(X2) | ~ relation(X2))) | (~ function(X1) | ~ relation(X1))), inference(ennf_transformation, [], [f37])).
fof(f37, plain, ! [X0, X1] : ((function(X1) & relation(X1)) => ! [X2] : ((function(X2) & relation(X2)) => ((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : (in(X3, relation_dom(X1)) => (apply(X2, X3) = apply(X1, X3))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))))), inference(rectify, [], [f35])).
fof(f35, plain, ! [X0, X1] : ((function(X1) & relation(X1)) => ! [X2] : ((function(X2) & relation(X2)) => ((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : (in(X3, relation_dom(X1)) => (apply(X2, X3) = apply(X1, X3))) & ! [X3] : (in(X3, relation_dom(X1)) <=> (in(apply(X2, X3), X0) & in(X3, relation_dom(X2)))))))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU045+1.p', t85_funct_1)).
fof(f166, plain, ! [X0, X1] : (~ sP1(X0, X1, relation_rng_restriction(X0, X1)) | sP0(relation_rng_restriction(X0, X1), X1, X0)), inference(equality_resolution, [], [f153])).
fof(f153, plain, ! [X2, X0, X1] : (sP0(X2, X1, X0) | ~ (relation_rng_restriction(X0, X1) = X2) | ~ sP1(X0, X1, X2)), inference(cnf_transformation, [], [f97])).
fof(f97, plain, ! [X0, X1, X2] : ((((relation_rng_restriction(X0, X1) = X2) | ~ sP0(X2, X1, X0)) & (sP0(X2, X1, X0) | ~ (relation_rng_restriction(X0, X1) = X2))) | ~ sP1(X0, X1, X2)), inference(rectify, [], [f96])).
fof(f96, plain, ! [X0, X2, X1] : ((((relation_rng_restriction(X0, X2) = X1) | ~ sP0(X1, X2, X0)) & (sP0(X1, X2, X0) | ~ (relation_rng_restriction(X0, X2) = X1))) | ~ sP1(X0, X2, X1)), inference(nnf_transformation, [], [f70])).
fof(f152, plain, ~ (apply(relation_rng_restriction(sK13, sK15), sK14) = apply(sK15, sK14)), inference(cnf_transformation, [], [f95])).