fof(f17523, plain, $false, inference(avatar_sat_refutation, [], [f194, f17449, f17521])).
fof(f17521, plain, spl18_2, inference(avatar_contradiction_clause, [], [f17520])).
fof(f17520, plain, ($false | spl18_2), inference(subsumption_resolution, [], [f17517, f181])).
fof(f181, plain, relation(sK17), inference(cnf_transformation, [], [f115])).
fof(f115, plain, ((~ subset(relation_rng(relation_rng_restriction(sK16, sK17)), relation_rng(sK17)) | ~ subset(relation_dom(relation_rng_restriction(sK16, sK17)), relation_dom(sK17))) & function(sK17) & relation(sK17)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK16, sK17])], [f74, f114])).
fof(f114, plain, (? [X0, X1] : ((~ subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) | ~ subset(relation_dom(relation_rng_restriction(X0, X1)), relation_dom(X1))) & function(X1) & relation(X1)) => ((~ subset(relation_rng(relation_rng_restriction(sK16, sK17)), relation_rng(sK17)) | ~ subset(relation_dom(relation_rng_restriction(sK16, sK17)), relation_dom(sK17))) & function(sK17) & relation(sK17))), introduced(choice_axiom, [])).
fof(f74, plain, ? [X0, X1] : ((~ subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) | ~ subset(relation_dom(relation_rng_restriction(X0, X1)), relation_dom(X1))) & function(X1) & relation(X1)), inference(flattening, [], [f73])).
fof(f73, plain, ? [X0, X1] : ((~ subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) | ~ subset(relation_dom(relation_rng_restriction(X0, X1)), relation_dom(X1))) & (function(X1) & relation(X1))), inference(ennf_transformation, [], [f38])).
fof(f38, plain, ~ ! [X0, X1] : ((function(X1) & relation(X1)) => (subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) & subset(relation_dom(relation_rng_restriction(X0, X1)), relation_dom(X1)))), inference(negated_conjecture, [], [f37])).
fof(f37, plain, ~ ! [X0, X1] : ((function(X1) & relation(X1)) => (subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) & subset(relation_dom(relation_rng_restriction(X0, X1)), relation_dom(X1)))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU046+1.p', t89_funct_1)).
fof(f17517, plain, (~ relation(sK17) | spl18_2), inference(resolution, [], [f193, f159])).
fof(f159, plain, ! [X0, X1] : (subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) | ~ relation(X1)), inference(cnf_transformation, [], [f62])).
fof(f62, plain, ! [X0, X1] : (subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1)) | ~ relation(X1)), inference(ennf_transformation, [], [f28])).
fof(f28, plain, ! [X0, X1] : (relation(X1) => subset(relation_rng(relation_rng_restriction(X0, X1)), relation_rng(X1))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU046+1.p', t118_relat_1)).
fof(f193, plain, (~ subset(relation_rng(relation_rng_restriction(sK16, sK17)), relation_rng(sK17)) | spl18_2), inference(avatar_component_clause, [], [f191])).
fof(f191, plain, (spl18_2 <=> subset(relation_rng(relation_rng_restriction(sK16, sK17)), relation_rng(sK17))), introduced(avatar_definition, [new_symbols(naming, [spl18_2])])).
fof(f17449, plain, spl18_1, inference(avatar_contradiction_clause, [], [f17448])).
fof(f17448, plain, ($false | spl18_1), inference(subsumption_resolution, [], [f17447, f182])).
fof(f182, plain, function(sK17), inference(cnf_transformation, [], [f115])).
fof(f17447, plain, (~ function(sK17) | spl18_1), inference(subsumption_resolution, [], [f17436, f181])).
fof(f17436, plain, (~ relation(sK17) | ~ function(sK17) | spl18_1), inference(resolution, [], [f4548, f189])).
fof(f189, plain, (~ subset(relation_dom(relation_rng_restriction(sK16, sK17)), relation_dom(sK17)) | spl18_1), inference(avatar_component_clause, [], [f187])).
fof(f187, plain, (spl18_1 <=> subset(relation_dom(relation_rng_restriction(sK16, sK17)), relation_dom(sK17))), introduced(avatar_definition, [new_symbols(naming, [spl18_1])])).
fof(f4548, plain, ! [X12, X13] : (subset(relation_dom(relation_rng_restriction(X13, X12)), relation_dom(X12)) | ~ relation(X12) | ~ function(X12)), inference(duplicate_literal_removal, [], [f4539])).
fof(f4539, plain, ! [X12, X13] : (~ function(X12) | ~ relation(X12) | subset(relation_dom(relation_rng_restriction(X13, X12)), relation_dom(X12)) | subset(relation_dom(relation_rng_restriction(X13, X12)), relation_dom(X12))), inference(resolution, [], [f1039, f123])).
fof(f123, plain, ! [X0, X1] : (~ in(sK2(X0, X1), X1) | subset(X0, X1)), inference(cnf_transformation, [], [f82])).
fof(f82, plain, ! [X0, X1] : ((subset(X0, X1) | (~ in(sK2(X0, X1), X1) & in(sK2(X0, X1), X0))) & (! [X3] : (in(X3, X1) | ~ in(X3, X0)) | ~ subset(X0, X1))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK2])], [f80, f81])).
fof(f81, plain, ! [X1, X0] : (? [X2] : (~ in(X2, X1) & in(X2, X0)) => (~ in(sK2(X0, X1), X1) & in(sK2(X0, X1), X0))), introduced(choice_axiom, [])).
fof(f80, plain, ! [X0, X1] : ((subset(X0, X1) | ? [X2] : (~ in(X2, X1) & in(X2, X0))) & (! [X3] : (in(X3, X1) | ~ in(X3, X0)) | ~ subset(X0, X1))), inference(rectify, [], [f79])).
fof(f79, plain, ! [X0, X1] : ((subset(X0, X1) | ? [X2] : (~ in(X2, X1) & in(X2, X0))) & (! [X2] : (in(X2, X1) | ~ in(X2, X0)) | ~ subset(X0, X1))), inference(nnf_transformation, [], [f51])).
fof(f51, plain, ! [X0, X1] : (subset(X0, X1) <=> ! [X2] : (in(X2, X1) | ~ in(X2, X0))), inference(ennf_transformation, [], [f5])).
fof(f5, plain, ! [X0, X1] : (subset(X0, X1) <=> ! [X2] : (in(X2, X0) => in(X2, X1))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU046+1.p', d3_tarski)).
fof(f1039, plain, ! [X14, X12, X13] : (in(sK2(relation_dom(relation_rng_restriction(X13, X12)), X14), relation_dom(X12)) | ~ function(X12) | ~ relation(X12) | subset(relation_dom(relation_rng_restriction(X13, X12)), X14)), inference(resolution, [], [f453, f122])).
fof(f122, plain, ! [X0, X1] : (in(sK2(X0, X1), X0) | subset(X0, X1)), inference(cnf_transformation, [], [f82])).
fof(f453, plain, ! [X6, X8, X7] : (~ in(X7, relation_dom(relation_rng_restriction(X8, X6))) | ~ relation(X6) | ~ function(X6) | in(X7, relation_dom(X6))), inference(resolution, [], [f301, f170])).
fof(f170, plain, ! [X6, X2, X0, X1] : (~ sP0(X0, X1, X2) | ~ in(X6, relation_dom(X0)) | in(X6, relation_dom(X1))), inference(cnf_transformation, [], [f113])).
fof(f113, plain, ! [X0, X1, X2] : ((sP0(X0, X1, X2) | (~ (apply(X1, sK14(X0, X1)) = apply(X0, sK14(X0, X1))) & in(sK14(X0, X1), relation_dom(X0))) | ((~ in(apply(X1, sK15(X0, X1, X2)), X2) | ~ in(sK15(X0, X1, X2), relation_dom(X1)) | ~ in(sK15(X0, X1, X2), relation_dom(X0))) & ((in(apply(X1, sK15(X0, X1, X2)), X2) & in(sK15(X0, X1, X2), relation_dom(X1))) | in(sK15(X0, X1, X2), relation_dom(X0))))) & ((! [X5] : ((apply(X1, X5) = apply(X0, X5)) | ~ in(X5, relation_dom(X0))) & ! [X6] : ((in(X6, relation_dom(X0)) | ~ in(apply(X1, X6), X2) | ~ in(X6, relation_dom(X1))) & ((in(apply(X1, X6), X2) & in(X6, relation_dom(X1))) | ~ in(X6, relation_dom(X0))))) | ~ sP0(X0, X1, X2))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK14, sK15])], [f110, f112, f111])).
fof(f111, plain, ! [X1, X0] : (? [X3] : (~ (apply(X1, X3) = apply(X0, X3)) & in(X3, relation_dom(X0))) => (~ (apply(X1, sK14(X0, X1)) = apply(X0, sK14(X0, X1))) & in(sK14(X0, X1), relation_dom(X0)))), introduced(choice_axiom, [])).
fof(f112, plain, ! [X2, X1, X0] : (? [X4] : ((~ in(apply(X1, X4), X2) | ~ in(X4, relation_dom(X1)) | ~ in(X4, relation_dom(X0))) & ((in(apply(X1, X4), X2) & in(X4, relation_dom(X1))) | in(X4, relation_dom(X0)))) => ((~ in(apply(X1, sK15(X0, X1, X2)), X2) | ~ in(sK15(X0, X1, X2), relation_dom(X1)) | ~ in(sK15(X0, X1, X2), relation_dom(X0))) & ((in(apply(X1, sK15(X0, X1, X2)), X2) & in(sK15(X0, X1, X2), relation_dom(X1))) | in(sK15(X0, X1, X2), relation_dom(X0))))), introduced(choice_axiom, [])).
fof(f110, plain, ! [X0, X1, X2] : ((sP0(X0, X1, X2) | ? [X3] : (~ (apply(X1, X3) = apply(X0, X3)) & in(X3, relation_dom(X0))) | ? [X4] : ((~ in(apply(X1, X4), X2) | ~ in(X4, relation_dom(X1)) | ~ in(X4, relation_dom(X0))) & ((in(apply(X1, X4), X2) & in(X4, relation_dom(X1))) | in(X4, relation_dom(X0))))) & ((! [X5] : ((apply(X1, X5) = apply(X0, X5)) | ~ in(X5, relation_dom(X0))) & ! [X6] : ((in(X6, relation_dom(X0)) | ~ in(apply(X1, X6), X2) | ~ in(X6, relation_dom(X1))) & ((in(apply(X1, X6), X2) & in(X6, relation_dom(X1))) | ~ in(X6, relation_dom(X0))))) | ~ sP0(X0, X1, X2))), inference(rectify, [], [f109])).
fof(f109, plain, ! [X1, X2, X0] : ((sP0(X1, X2, X0) | ? [X3] : (~ (apply(X2, X3) = apply(X1, X3)) & in(X3, relation_dom(X1))) | ? [X4] : ((~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2)) | ~ in(X4, relation_dom(X1))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | in(X4, relation_dom(X1))))) & ((! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : ((in(X4, relation_dom(X1)) | ~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | ~ in(X4, relation_dom(X1))))) | ~ sP0(X1, X2, X0))), inference(flattening, [], [f108])).
fof(f108, plain, ! [X1, X2, X0] : ((sP0(X1, X2, X0) | (? [X3] : (~ (apply(X2, X3) = apply(X1, X3)) & in(X3, relation_dom(X1))) | ? [X4] : (((~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2))) | ~ in(X4, relation_dom(X1))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | in(X4, relation_dom(X1)))))) & ((! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : ((in(X4, relation_dom(X1)) | (~ in(apply(X2, X4), X0) | ~ in(X4, relation_dom(X2)))) & ((in(apply(X2, X4), X0) & in(X4, relation_dom(X2))) | ~ in(X4, relation_dom(X1))))) | ~ sP0(X1, X2, X0))), inference(nnf_transformation, [], [f76])).
fof(f76, plain, ! [X1, X2, X0] : (sP0(X1, X2, X0) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))), inference(usedef, [], [e76])).
fof(e76, plain, ! [X1, X2, X0] : (sP0(X1, X2, X0) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP0])])).
fof(f301, plain, ! [X0, X1] : (sP0(relation_rng_restriction(X0, X1), X1, X0) | ~ function(X1) | ~ relation(X1)), inference(subsumption_resolution, [], [f300, f124])).
fof(f124, plain, ! [X0, X1] : (relation(relation_rng_restriction(X0, X1)) | ~ relation(X1)), inference(cnf_transformation, [], [f52])).
fof(f52, plain, ! [X0, X1] : (relation(relation_rng_restriction(X0, X1)) | ~ relation(X1)), inference(ennf_transformation, [], [f6])).
fof(f6, plain, ! [X0, X1] : (relation(X1) => relation(relation_rng_restriction(X0, X1))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU046+1.p', dt_k8_relat_1)).
fof(f300, plain, ! [X0, X1] : (sP0(relation_rng_restriction(X0, X1), X1, X0) | ~ function(X1) | ~ relation(X1) | ~ relation(relation_rng_restriction(X0, X1))), inference(subsumption_resolution, [], [f299, f133])).
fof(f133, plain, ! [X0, X1] : (function(relation_rng_restriction(X0, X1)) | ~ function(X1) | ~ relation(X1)), inference(cnf_transformation, [], [f54])).
fof(f54, plain, ! [X0, X1] : ((function(relation_rng_restriction(X0, X1)) & relation(relation_rng_restriction(X0, X1))) | ~ function(X1) | ~ relation(X1)), inference(flattening, [], [f53])).
fof(f53, plain, ! [X0, X1] : ((function(relation_rng_restriction(X0, X1)) & relation(relation_rng_restriction(X0, X1))) | (~ function(X1) | ~ relation(X1))), inference(ennf_transformation, [], [f12])).
fof(f12, plain, ! [X0, X1] : ((function(X1) & relation(X1)) => (function(relation_rng_restriction(X0, X1)) & relation(relation_rng_restriction(X0, X1)))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU046+1.p', fc5_funct_1)).
fof(f299, plain, ! [X0, X1] : (sP0(relation_rng_restriction(X0, X1), X1, X0) | ~ function(X1) | ~ relation(X1) | ~ function(relation_rng_restriction(X0, X1)) | ~ relation(relation_rng_restriction(X0, X1))), inference(resolution, [], [f185, f180])).
fof(f180, plain, ! [X2, X0, X1] : (sP1(X0, X2, X1) | ~ function(X2) | ~ relation(X2) | ~ function(X1) | ~ relation(X1)), inference(cnf_transformation, [], [f78])).
fof(f78, plain, ! [X0, X1] : (! [X2] : (sP1(X0, X2, X1) | ~ function(X2) | ~ relation(X2)) | ~ function(X1) | ~ relation(X1)), inference(definition_folding, [], [f72, e77, e76])).
fof(f77, plain, ! [X0, X2, X1] : (((relation_rng_restriction(X0, X2) = X1) <=> sP0(X1, X2, X0)) | ~ sP1(X0, X2, X1)), inference(usedef, [], [e77])).
fof(e77, plain, ! [X0, X2, X1] : (sP1(X0, X2, X1) <=> ((relation_rng_restriction(X0, X2) = X1) <=> sP0(X1, X2, X0))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP1])])).
fof(f72, plain, ! [X0, X1] : (! [X2] : (((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))) | ~ function(X2) | ~ relation(X2)) | ~ function(X1) | ~ relation(X1)), inference(flattening, [], [f71])).
fof(f71, plain, ! [X0, X1] : (! [X2] : (((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : ((apply(X2, X3) = apply(X1, X3)) | ~ in(X3, relation_dom(X1))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))) | (~ function(X2) | ~ relation(X2))) | (~ function(X1) | ~ relation(X1))), inference(ennf_transformation, [], [f41])).
fof(f41, plain, ! [X0, X1] : ((function(X1) & relation(X1)) => ! [X2] : ((function(X2) & relation(X2)) => ((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : (in(X3, relation_dom(X1)) => (apply(X2, X3) = apply(X1, X3))) & ! [X4] : (in(X4, relation_dom(X1)) <=> (in(apply(X2, X4), X0) & in(X4, relation_dom(X2)))))))), inference(rectify, [], [f36])).
fof(f36, plain, ! [X0, X1] : ((function(X1) & relation(X1)) => ! [X2] : ((function(X2) & relation(X2)) => ((relation_rng_restriction(X0, X2) = X1) <=> (! [X3] : (in(X3, relation_dom(X1)) => (apply(X2, X3) = apply(X1, X3))) & ! [X3] : (in(X3, relation_dom(X1)) <=> (in(apply(X2, X3), X0) & in(X3, relation_dom(X2)))))))), file('/home/ubuntu/library/tptp/Problems/SEU/SEU046+1.p', t85_funct_1)).
fof(f185, plain, ! [X0, X1] : (~ sP1(X0, X1, relation_rng_restriction(X0, X1)) | sP0(relation_rng_restriction(X0, X1), X1, X0)), inference(equality_resolution, [], [f168])).
fof(f168, plain, ! [X2, X0, X1] : (sP0(X2, X1, X0) | ~ (relation_rng_restriction(X0, X1) = X2) | ~ sP1(X0, X1, X2)), inference(cnf_transformation, [], [f107])).
fof(f107, plain, ! [X0, X1, X2] : ((((relation_rng_restriction(X0, X1) = X2) | ~ sP0(X2, X1, X0)) & (sP0(X2, X1, X0) | ~ (relation_rng_restriction(X0, X1) = X2))) | ~ sP1(X0, X1, X2)), inference(rectify, [], [f106])).
fof(f106, plain, ! [X0, X2, X1] : ((((relation_rng_restriction(X0, X2) = X1) | ~ sP0(X1, X2, X0)) & (sP0(X1, X2, X0) | ~ (relation_rng_restriction(X0, X2) = X1))) | ~ sP1(X0, X2, X1)), inference(nnf_transformation, [], [f77])).
fof(f194, plain, (~ spl18_1 | ~ spl18_2), inference(avatar_split_clause, [], [f183, f191, f187])).
fof(f183, plain, (~ subset(relation_rng(relation_rng_restriction(sK16, sK17)), relation_rng(sK17)) | ~ subset(relation_dom(relation_rng_restriction(sK16, sK17)), relation_dom(sK17))), inference(cnf_transformation, [], [f115])).