fof(f374, plain, $false, inference(subsumption_resolution, [], [f373, f283])).
fof(f283, plain, icext(uri_ex_A, uri_ex_w), inference(resolution, [], [f266, f60])).
fof(f60, plain, icext(sK3, uri_ex_w), inference(resolution, [], [f28, f49])).
fof(f49, plain, iext(uri_rdf_type, uri_ex_w, sK3), inference(cnf_transformation, [], [f27])).
fof(f27, plain, (iext(uri_owl_complementOf, sK4, uri_ex_A) & iext(uri_rdf_rest, sK6, uri_rdf_nil) & iext(uri_rdf_first, sK6, sK4) & iext(uri_rdf_rest, sK5, sK6) & iext(uri_rdf_first, sK5, uri_ex_A) & iext(uri_owl_intersectionOf, sK3, sK5) & iext(uri_rdf_type, uri_ex_w, sK3) & iext(uri_rdf_type, uri_ex_B, uri_owl_Class) & iext(uri_rdf_type, uri_ex_A, uri_owl_Class)), inference(skolemisation, [status(esa), new_symbols(skolem, [sK3, sK4, sK5, sK6])], [f10, f26])).
fof(f26, plain, (? [X0, X1, X2, X3] : (iext(uri_owl_complementOf, X1, uri_ex_A) & iext(uri_rdf_rest, X3, uri_rdf_nil) & iext(uri_rdf_first, X3, X1) & iext(uri_rdf_rest, X2, X3) & iext(uri_rdf_first, X2, uri_ex_A) & iext(uri_owl_intersectionOf, X0, X2) & iext(uri_rdf_type, uri_ex_w, X0) & iext(uri_rdf_type, uri_ex_B, uri_owl_Class) & iext(uri_rdf_type, uri_ex_A, uri_owl_Class)) => (iext(uri_owl_complementOf, sK4, uri_ex_A) & iext(uri_rdf_rest, sK6, uri_rdf_nil) & iext(uri_rdf_first, sK6, sK4) & iext(uri_rdf_rest, sK5, sK6) & iext(uri_rdf_first, sK5, uri_ex_A) & iext(uri_owl_intersectionOf, sK3, sK5) & iext(uri_rdf_type, uri_ex_w, sK3) & iext(uri_rdf_type, uri_ex_B, uri_owl_Class) & iext(uri_rdf_type, uri_ex_A, uri_owl_Class))), introduced(choice_axiom, [])).
fof(f10, plain, ? [X0, X1, X2, X3] : (iext(uri_owl_complementOf, X1, uri_ex_A) & iext(uri_rdf_rest, X3, uri_rdf_nil) & iext(uri_rdf_first, X3, X1) & iext(uri_rdf_rest, X2, X3) & iext(uri_rdf_first, X2, uri_ex_A) & iext(uri_owl_intersectionOf, X0, X2) & iext(uri_rdf_type, uri_ex_w, X0) & iext(uri_rdf_type, uri_ex_B, uri_owl_Class) & iext(uri_rdf_type, uri_ex_A, uri_owl_Class)), inference(rectify, [], [f6])).
fof(f6, plain, ? [X7, X8, X9, X10] : (iext(uri_owl_complementOf, X8, uri_ex_A) & iext(uri_rdf_rest, X10, uri_rdf_nil) & iext(uri_rdf_first, X10, X8) & iext(uri_rdf_rest, X9, X10) & iext(uri_rdf_first, X9, uri_ex_A) & iext(uri_owl_intersectionOf, X7, X9) & iext(uri_rdf_type, uri_ex_w, X7) & iext(uri_rdf_type, uri_ex_B, uri_owl_Class) & iext(uri_rdf_type, uri_ex_A, uri_owl_Class)), file('/home/ubuntu/library/tptp/Problems/SWB/SWB029+2.p', testcase_premise_fullish_029_Ex_Falso_Quodlibet)).
fof(f28, plain, ! [X0, X1] : (~ iext(uri_rdf_type, X0, X1) | icext(X1, X0)), inference(cnf_transformation, [], [f17])).
fof(f17, plain, ! [X0, X1] : ((iext(uri_rdf_type, X0, X1) | ~ icext(X1, X0)) & (icext(X1, X0) | ~ iext(uri_rdf_type, X0, X1))), inference(nnf_transformation, [], [f1])).
fof(f1, plain, ! [X0, X1] : (iext(uri_rdf_type, X0, X1) <=> icext(X1, X0)), file('/home/ubuntu/library/tptp/Problems/SWB/SWB029+2.p', rdfs_cext_def)).
fof(f266, plain, ! [X0] : (~ icext(sK3, X0) | icext(uri_ex_A, X0)), inference(resolution, [], [f251, f39])).
fof(f39, plain, ! [X4, X2, X0, X1] : (~ sP0(X0, X1, X2) | ~ icext(X2, X4) | icext(X1, X4)), inference(cnf_transformation, [], [f25])).
fof(f25, plain, ! [X0, X1, X2] : ((sP0(X0, X1, X2) | ((~ icext(X0, sK2(X0, X1, X2)) | ~ icext(X1, sK2(X0, X1, X2)) | ~ icext(X2, sK2(X0, X1, X2))) & ((icext(X0, sK2(X0, X1, X2)) & icext(X1, sK2(X0, X1, X2))) | icext(X2, sK2(X0, X1, X2)))) | ~ ic(X0) | ~ ic(X1) | ~ ic(X2)) & ((! [X4] : ((icext(X2, X4) | ~ icext(X0, X4) | ~ icext(X1, X4)) & ((icext(X0, X4) & icext(X1, X4)) | ~ icext(X2, X4))) & ic(X0) & ic(X1) & ic(X2)) | ~ sP0(X0, X1, X2))), inference(skolemisation, [status(esa), new_symbols(skolem, [sK2])], [f23, f24])).
fof(f24, plain, ! [X2, X1, X0] : (? [X3] : ((~ icext(X0, X3) | ~ icext(X1, X3) | ~ icext(X2, X3)) & ((icext(X0, X3) & icext(X1, X3)) | icext(X2, X3))) => ((~ icext(X0, sK2(X0, X1, X2)) | ~ icext(X1, sK2(X0, X1, X2)) | ~ icext(X2, sK2(X0, X1, X2))) & ((icext(X0, sK2(X0, X1, X2)) & icext(X1, sK2(X0, X1, X2))) | icext(X2, sK2(X0, X1, X2))))), introduced(choice_axiom, [])).
fof(f23, plain, ! [X0, X1, X2] : ((sP0(X0, X1, X2) | ? [X3] : ((~ icext(X0, X3) | ~ icext(X1, X3) | ~ icext(X2, X3)) & ((icext(X0, X3) & icext(X1, X3)) | icext(X2, X3))) | ~ ic(X0) | ~ ic(X1) | ~ ic(X2)) & ((! [X4] : ((icext(X2, X4) | ~ icext(X0, X4) | ~ icext(X1, X4)) & ((icext(X0, X4) & icext(X1, X4)) | ~ icext(X2, X4))) & ic(X0) & ic(X1) & ic(X2)) | ~ sP0(X0, X1, X2))), inference(rectify, [], [f22])).
fof(f22, plain, ! [X4, X2, X0] : ((sP0(X4, X2, X0) | ? [X5] : ((~ icext(X4, X5) | ~ icext(X2, X5) | ~ icext(X0, X5)) & ((icext(X4, X5) & icext(X2, X5)) | icext(X0, X5))) | ~ ic(X4) | ~ ic(X2) | ~ ic(X0)) & ((! [X5] : ((icext(X0, X5) | ~ icext(X4, X5) | ~ icext(X2, X5)) & ((icext(X4, X5) & icext(X2, X5)) | ~ icext(X0, X5))) & ic(X4) & ic(X2) & ic(X0)) | ~ sP0(X4, X2, X0))), inference(flattening, [], [f21])).
fof(f21, plain, ! [X4, X2, X0] : ((sP0(X4, X2, X0) | (? [X5] : (((~ icext(X4, X5) | ~ icext(X2, X5)) | ~ icext(X0, X5)) & ((icext(X4, X5) & icext(X2, X5)) | icext(X0, X5))) | ~ ic(X4) | ~ ic(X2) | ~ ic(X0))) & ((! [X5] : ((icext(X0, X5) | (~ icext(X4, X5) | ~ icext(X2, X5))) & ((icext(X4, X5) & icext(X2, X5)) | ~ icext(X0, X5))) & ic(X4) & ic(X2) & ic(X0)) | ~ sP0(X4, X2, X0))), inference(nnf_transformation, [], [f14])).
fof(f14, plain, ! [X4, X2, X0] : (sP0(X4, X2, X0) <=> (! [X5] : (icext(X0, X5) <=> (icext(X4, X5) & icext(X2, X5))) & ic(X4) & ic(X2) & ic(X0))), inference(usedef, [], [e14])).
fof(e14, plain, ! [X4, X2, X0] : (sP0(X4, X2, X0) <=> (! [X5] : (icext(X0, X5) <=> (icext(X4, X5) & icext(X2, X5))) & ic(X4) & ic(X2) & ic(X0))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP0])])).
fof(f251, plain, sP0(sK4, uri_ex_A, sK3), inference(resolution, [], [f234, f51])).
fof(f51, plain, iext(uri_rdf_first, sK5, uri_ex_A), inference(cnf_transformation, [], [f27])).
fof(f234, plain, ! [X0] : (~ iext(uri_rdf_first, sK5, X0) | sP0(sK4, X0, sK3)), inference(resolution, [], [f233, f53])).
fof(f53, plain, iext(uri_rdf_first, sK6, sK4), inference(cnf_transformation, [], [f27])).
fof(f233, plain, ! [X0, X1] : (~ iext(uri_rdf_first, sK6, X1) | ~ iext(uri_rdf_first, sK5, X0) | sP0(X1, X0, sK3)), inference(subsumption_resolution, [], [f232, f52])).
fof(f52, plain, iext(uri_rdf_rest, sK5, sK6), inference(cnf_transformation, [], [f27])).
fof(f232, plain, ! [X0, X1] : (~ iext(uri_rdf_rest, sK5, sK6) | ~ iext(uri_rdf_first, sK5, X0) | ~ iext(uri_rdf_first, sK6, X1) | sP0(X1, X0, sK3)), inference(resolution, [], [f102, f50])).
fof(f50, plain, iext(uri_owl_intersectionOf, sK3, sK5), inference(cnf_transformation, [], [f27])).
fof(f102, plain, ! [X6, X4, X7, X5] : (~ iext(uri_owl_intersectionOf, X7, X5) | ~ iext(uri_rdf_rest, X5, sK6) | ~ iext(uri_rdf_first, X5, X6) | ~ iext(uri_rdf_first, sK6, X4) | sP0(X4, X6, X7)), inference(resolution, [], [f66, f34])).
fof(f34, plain, ! [X2, X0, X3, X1] : (~ sP1(X0, X1, X2, X3) | ~ iext(uri_owl_intersectionOf, X0, X3) | sP0(X2, X1, X0)), inference(cnf_transformation, [], [f20])).
fof(f20, plain, ! [X0, X1, X2, X3] : (((iext(uri_owl_intersectionOf, X0, X3) | ~ sP0(X2, X1, X0)) & (sP0(X2, X1, X0) | ~ iext(uri_owl_intersectionOf, X0, X3))) | ~ sP1(X0, X1, X2, X3)), inference(rectify, [], [f19])).
fof(f19, plain, ! [X0, X2, X4, X1] : (((iext(uri_owl_intersectionOf, X0, X1) | ~ sP0(X4, X2, X0)) & (sP0(X4, X2, X0) | ~ iext(uri_owl_intersectionOf, X0, X1))) | ~ sP1(X0, X2, X4, X1)), inference(nnf_transformation, [], [f15])).
fof(f15, plain, ! [X0, X2, X4, X1] : ((iext(uri_owl_intersectionOf, X0, X1) <=> sP0(X4, X2, X0)) | ~ sP1(X0, X2, X4, X1)), inference(usedef, [], [e15])).
fof(e15, plain, ! [X0, X2, X4, X1] : (sP1(X0, X2, X4, X1) <=> (iext(uri_owl_intersectionOf, X0, X1) <=> sP0(X4, X2, X0))), introduced(predicate_definition_introduction, [new_symbols(naming, [sP1])])).
fof(f66, plain, ! [X2, X0, X3, X1] : (sP1(X0, X1, X2, X3) | ~ iext(uri_rdf_first, sK6, X2) | ~ iext(uri_rdf_rest, X3, sK6) | ~ iext(uri_rdf_first, X3, X1)), inference(resolution, [], [f45, f54])).
fof(f54, plain, iext(uri_rdf_rest, sK6, uri_rdf_nil), inference(cnf_transformation, [], [f27])).
fof(f45, plain, ! [X4, X2, X0, X3, X1] : (~ iext(uri_rdf_rest, X3, uri_rdf_nil) | sP1(X0, X2, X4, X1) | ~ iext(uri_rdf_first, X3, X4) | ~ iext(uri_rdf_rest, X1, X3) | ~ iext(uri_rdf_first, X1, X2)), inference(cnf_transformation, [], [f16])).
fof(f16, plain, ! [X0, X1, X2, X3, X4] : (sP1(X0, X2, X4, X1) | ~ iext(uri_rdf_rest, X3, uri_rdf_nil) | ~ iext(uri_rdf_first, X3, X4) | ~ iext(uri_rdf_rest, X1, X3) | ~ iext(uri_rdf_first, X1, X2)), inference(definition_folding, [], [f13, e15, e14])).
fof(f13, plain, ! [X0, X1, X2, X3, X4] : ((iext(uri_owl_intersectionOf, X0, X1) <=> (! [X5] : (icext(X0, X5) <=> (icext(X4, X5) & icext(X2, X5))) & ic(X4) & ic(X2) & ic(X0))) | ~ iext(uri_rdf_rest, X3, uri_rdf_nil) | ~ iext(uri_rdf_first, X3, X4) | ~ iext(uri_rdf_rest, X1, X3) | ~ iext(uri_rdf_first, X1, X2)), inference(flattening, [], [f12])).
fof(f12, plain, ! [X0, X1, X2, X3, X4] : ((iext(uri_owl_intersectionOf, X0, X1) <=> (! [X5] : (icext(X0, X5) <=> (icext(X4, X5) & icext(X2, X5))) & ic(X4) & ic(X2) & ic(X0))) | (~ iext(uri_rdf_rest, X3, uri_rdf_nil) | ~ iext(uri_rdf_first, X3, X4) | ~ iext(uri_rdf_rest, X1, X3) | ~ iext(uri_rdf_first, X1, X2))), inference(ennf_transformation, [], [f8])).
fof(f8, plain, ! [X0, X1, X2, X3, X4] : ((iext(uri_rdf_rest, X3, uri_rdf_nil) & iext(uri_rdf_first, X3, X4) & iext(uri_rdf_rest, X1, X3) & iext(uri_rdf_first, X1, X2)) => (iext(uri_owl_intersectionOf, X0, X1) <=> (! [X5] : (icext(X0, X5) <=> (icext(X4, X5) & icext(X2, X5))) & ic(X4) & ic(X2) & ic(X0)))), inference(rectify, [], [f3])).
fof(f3, plain, ! [X2, X3, X4, X5, X6] : ((iext(uri_rdf_rest, X5, uri_rdf_nil) & iext(uri_rdf_first, X5, X6) & iext(uri_rdf_rest, X3, X5) & iext(uri_rdf_first, X3, X4)) => (iext(uri_owl_intersectionOf, X2, X3) <=> (! [X0] : (icext(X2, X0) <=> (icext(X6, X0) & icext(X4, X0))) & ic(X6) & ic(X4) & ic(X2)))), file('/home/ubuntu/library/tptp/Problems/SWB/SWB029+2.p', owl_bool_intersectionof_class_002)).
fof(f373, plain, ~ icext(uri_ex_A, uri_ex_w), inference(resolution, [], [f336, f63])).
fof(f63, plain, ! [X0] : (~ icext(sK4, X0) | ~ icext(uri_ex_A, X0)), inference(resolution, [], [f32, f55])).
fof(f55, plain, iext(uri_owl_complementOf, sK4, uri_ex_A), inference(cnf_transformation, [], [f27])).
fof(f32, plain, ! [X2, X0, X1] : (~ iext(uri_owl_complementOf, X0, X1) | ~ icext(X0, X2) | ~ icext(X1, X2)), inference(cnf_transformation, [], [f18])).
fof(f18, plain, ! [X0, X1] : ((! [X2] : ((icext(X0, X2) | icext(X1, X2)) & (~ icext(X1, X2) | ~ icext(X0, X2))) & ic(X1) & ic(X0)) | ~ iext(uri_owl_complementOf, X0, X1)), inference(nnf_transformation, [], [f11])).
fof(f11, plain, ! [X0, X1] : ((! [X2] : (icext(X0, X2) <=> ~ icext(X1, X2)) & ic(X1) & ic(X0)) | ~ iext(uri_owl_complementOf, X0, X1)), inference(ennf_transformation, [], [f7])).
fof(f7, plain, ! [X0, X1] : (iext(uri_owl_complementOf, X0, X1) => (! [X2] : (icext(X0, X2) <=> ~ icext(X1, X2)) & ic(X1) & ic(X0))), inference(rectify, [], [f2])).
fof(f2, plain, ! [X2, X1] : (iext(uri_owl_complementOf, X2, X1) => (! [X0] : (icext(X2, X0) <=> ~ icext(X1, X0)) & ic(X1) & ic(X2))), file('/home/ubuntu/library/tptp/Problems/SWB/SWB029+2.p', owl_bool_complementof_class)).
fof(f336, plain, icext(sK4, uri_ex_w), inference(resolution, [], [f267, f60])).
fof(f267, plain, ! [X1] : (~ icext(sK3, X1) | icext(sK4, X1)), inference(resolution, [], [f251, f40])).
fof(f40, plain, ! [X4, X2, X0, X1] : (~ sP0(X0, X1, X2) | ~ icext(X2, X4) | icext(X0, X4)), inference(cnf_transformation, [], [f25])).